### ISSUE TITLE
Buying virtual good in editor does not fire StoreEvents.OnMarketPurchase

### ISSUE THREAD

**Issue by tenpn** [soomla/unity3d-store#399]
- run the game in the editor
- buy a market item with `StoreInventory.BuyItem(item)`
- if a single-use virtual good, notice you get the `OnGoodBalanceChanged` callback
- with either base virtual goods or single-use goods, you get no `OnMarketPurchase` callback 
- do the same thing on a device, and you get a `OnMarketPurchase` callback

A recent update advertised that the store worked in the editor, and I looked forward to not having #if UNITY_EDITOR exceptions sprinkled around my code. Is there an easy hack to get OnMarketPurchase callbacks in the editor?

**Comment by refaelos** [comment]
Do you still get this error?

**Comment by tenpn** [comment]
Nope no change in 1.7.7. Did you expect one?

**Comment by refaelos** [comment]
Can you take a look at the code and propose a solution?
If not, it'll take us some time but we'll do it.

**Comment by refaelos** [comment]
Closing this issue. Open if you need more help.
