### ISSUE TITLE
Repurchasing iOS non-consumable does not re-fire balance-changed or market-purchase events

### ISSUE THREAD

**Issue by tenpn** [soomla/unity3d-store#400]
- purchase a non-cosumable IAP on iOS
- delete the app, wiping the local storage
- reinstall and boot the app
- the app doesn't know that you own the non-consumable, and restoring purchases is as I understand it not automatic on iOS
- attempt to buy the non-consumable, get the "You will not be charged again" iOS pop-up, etc.
- the logging *implies* Soomla receives the non-consumable and stores it in the inventory, but GetItemBalance() returns 0, even on subsequent boots
- no OnMarketPurchase or OnGoodBalanceChanged events are fired

I'm using Soomla callbacks to bring down my "Please Wait" dialog and unpause the game. With no callback, I can't unpause. I'd like at least one of them to fire, preferably with some flag so I know it's a repurchase and can track that in analytics.

**Comment by tenpn** [comment]
If I attempt to restore purchases first, the restore returns success but soomla claims to not own no_ads. There are no callbacks but the logging looks similar to before:

    2015-01-02 18:08:15.180 app[272:60b] [Debug] SOOMLA SoomlaStore: Restore transaction for product: no_ads
    2015-01-02 18:08:15.182 app[272:60b] [Debug] SOOMLA VirtualGoodStorage: trying to fetch balance for virtual item with itemId: no_ads
    2015-01-02 18:08:15.188 app[272:60b] [Debug] SOOMLA VirtualGoodStorage: the balance for no_ads is: 1
    SOOMLA StoreEvents SOOMLA/UNITY onRestoreTransactionsFinished:{
      "success" : true
    }

Making the first iOS no_ads purchase on the account works, as does buying the consumable IAPs. 

On Android, attempting to re-purchase no_ads returns an error about already owning the item, which is acceptable. Restoring purchases succeeds, firing OnMarketPurchase and OnGoodBalanceChanged events. It's just iOS that is freaking out.

**Comment by refaelos** [comment]
You wrote a lot. It looks like you solved it on your own. Just call RestorePurchases when you want to restore them. 
Just so you know... Apple restrict automatic restore purchases and want you to add a button for this operation. If you automatically restore purchases they might decline your app submission.

Your call.

**Comment by tenpn** [comment]
Sorry, you mis-understand. I have _not_ solved it. Restore Purchases does not work, neither does a repurchase. Both output similar logging, but subsequently the inventory does not have the item. Even if one of these worked, both should. Please re-open the bug.

**Comment by refaelos** [comment]
Make sure you call restore transactions on store initialized event.

**Comment by tenpn** [comment]
You think that will have a different effect to when I'm already calling it, a few moments into the app reaching the main menu?

**Comment by refaelos** [comment]
yes.

**Comment by tenpn** [comment]
Had no effect - although it _didn't_ produce the restore logs from above, and "completed" despite the itunes sign-in dialog still being on the screen. no_ads still wasn't available after. A subsequent restore later in the session produced the logs from above, but still no no_ads.

**Comment by refaelos** [comment]
Several options:
- Try using v1.7.8 (latest).
- If you're testing, make sure "Test Purchases" is turned on.
- Catch all relevant events and let me know which are fired.
- Try looking at the logs again... they should give you a hint of a problem.

**Comment by tenpn** [comment]
I upgraded to latest and it now works.

**Comment by refaelos** [comment]
Perfect!
