### ISSUE TITLE
1 out of 2 purchases are working & forever 0.99 price

### ISSUE THREAD

**Issue by Mr1nf1n1ty** [soomla/unity3d-store#401]
So I have 2 currency packs the user can purchase in the MyAssets.cs code:
ONEKCOIN_PACK & TWOKCOIN_PACK

public const string ONEKCOIN_PACK_PRODUCT_ID = "android.test.purchased"; // testing id
public const string TWOKCOIN_PACK_PRODUCT_ID = "android.test.purchased"; // testing id

public static VirtualCurrencyPack ONEKCOIN_PACK = new VirtualCurrencyPack(
	"1000 Coins",
	"Purchase 1000 coins",
	"1000coin",
	1000,
	COIN_CURRENCY_ITEM_ID,
	new PurchaseWithMarket(ONEKCOIN_PACK_PRODUCT_ID, 3.99)
);
public static VirtualCurrencyPack TWOKCOIN_PACK = new VirtualCurrencyPack(
	"2000 Coins",
	"Purchase 2000 coins",
	"2000coin",
	2000,
	COIN_CURRENCY_ITEM_ID,
	new PurchaseWithMarket(TWOKCOIN_PACK_PRODUCT_ID, 7.99)
);

Unity3d throws this log and error out when I attempt to purchase the TWOKCOIN_PACK:

SOOMLA StoreInventory Buying: 2000coin
SOOMLA/UNITY StoreInfo Trying to fetch an item with itemId: 2000coin
VirtualItemNotFoundException: Virtual item was not found when searching with itemId=2000coin

ONEKCOIN_PACK works just fine but soomla cannot find TWOKCOIN_PACK, which is really weird as they both have the exact same lines of code save for the 1000 & 2000 differences

Also, the prices that I set in the Currency Packs (the 3.99 & 7.99), they'll always show up as 0.99 in the Google Play Store Page when I test in a mobile device, regardless of changing them in the actual codes or in the In-app Products in the Google Play Developer Console. (I've tried both android.test.purchased & the actual item Id in the developer console with the same results)

![forever 0 99](https://cloud.githubusercontent.com/assets/10431887/5642645/1f5e974a-9688-11e4-9f3e-91ee7b32642e.jpg)

It feels like I missed something somewhere and tried searching everywhere but with no avail, so here I am asking the Soomla peeps here. Thanks in advance and much appreciated~

**Comment by refaelos** [comment]
That's only because they both have the same product id... SOOMLA isn't able to find the right product when the purchase succeeds. Just test each one separately.
