### ISSUE TITLE
InsufficientFunds error

### ISSUE THREAD

**Issue by adryande** [soomla/unity3d-store#403]
Method checkTargetBalance does a ">" operation, instead of a ">=", so it doesn't allow to buy items when you have the exact amount of currency. Method should be fixed like this:

private bool checkTargetBalance (VirtualItem item)
{
	int balance = item.GetBalance ();
	// return balance > Amount;
	return balance >= Amount;
}

**Comment by gurdotan** [comment]
Nice. Can you submit a pull request? We'll gladly pull it in.

**Comment by adryande** [comment]
Of course, I just did it.

2015-01-15 19:25 GMT+01:00 Gur Dotan <notifications@github.com>:

**Comment by gurdotan** [comment]
Great thanks.

**Comment by sluzky** [comment]
Fixed here https://github.com/soomla/unity3d-store/commit/861e1cc0a76eefef5a797289a60f1fc98bb1d3d4, thanks @adryande!
