### ISSUE TITLE
Crash on ios with postMarketItemsRefreshFinished StoreEventHandling.m

### ISSUE THREAD

**Issue by CapelaGames** [soomla/unity3d-store#404]
Hey,
So I started getting the following error:

2015-01-16 13:26:27.158 FindAWordFury[1095:278832] Uncaught exception: NSInvalidArgumentException: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]
(
	0   CoreFoundation                      0x255d94b7 <redacted> + 150
	1   libobjc.A.dylib                     0x33061c8b objc_exception_throw + 38
	2   CoreFoundation                      0x254f9873 <redacted> + 502
	3   CoreFoundation                      0x254f9657 <redacted> + 50
	4   FindAWordFury                       0x01065607 -[UnityStoreEventDispatcher handleEvent:] + 3334
	5   CoreFoundation                      0x25591c61 <redacted> + 12
	6   CoreFoundation                      0x254ed6d5 _CFXNotificationPost + 1784
	7   Foundation                          0x2621f189 <redacted> + 72
	8   FindAWordFury                       0x0105d413 +[StoreEventHandling postMarketItemsRefreshFinished:] + 150
	9   FindAWordFury                       0x01061569 -[SoomlaStore productsRequest:didReceiveResponse:] + 2068
	10  StoreKit                            0x28a1f607 <redacted> + 494
	11  libdispatch.dylib                   0x03c639db _dispatch_call_block_and_release + 10
	12  libdispatch.dylib                   0x03c639c7 _dispatch_client_callout + 22
	13  libdispatch.dylib                   0x03c673ed _dispatch_main_queue_callback_4CF + 808
	14  CoreFoundation                      0x2559f3b1 <redacted> + 8
	15  CoreFoundation                      0x2559dab1 <redacted> + 1512
	16  CoreFoundation                      0x254eb3c1 CFRunLoopRunSpecific + 476
	17  CoreFoundation                      0x254eb1d3 CFRunLoopRunInMode + 106
	18  GraphicsServices                    0x2c8800a9 GSEventRunModal + 136
	19  UIKit                               0x28afafa1 UIApplicationMain + 1440
	20  FindAWordFury                       0x0000bd40 main + 308
	21  FindAWordFury                       0x0000bc08 start + 40
)
2015-01-16 13:26:27.160 FindAWordFury[1095:278832] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]'
*** First throw call stack:
(0x255d949f 0x33061c8b 0x254f9873 0x254f9657 0x1065607 0x25591c61 0x254ed6d5 0x2621f189 0x105d413 0x1061569 0x28a1f607 0x3c639db 0x3c639c7 0x3c673ed 0x2559f3b1 0x2559dab1 0x254eb3c1 0x254eb1d3 0x2c8800a9 0x28afafa1 0xbd40 0xbc08)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

I have created an empty scene with only Core Events, Store Events and a class that only fires off "SoomlaStore.Initialize(new IAPStoreAssets());" In Start().

I also have the latest Soomla. 
It seems to occur once I try to Initialize Soomla. Here is my IStoreAssets class:

using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Soomla.Store;

public class IAPStoreAssets : IStoreAssets 
{

	public int GetVersion()
	{
		return 8;
	}

	public VirtualCurrency[] GetCurrencies()
	{
		return new VirtualCurrency[]{};
	}

	public VirtualGood[] GetGoods() 
	{
		return new VirtualGood[] {PREMIUM};
	}

	public VirtualCurrencyPack[] GetCurrencyPacks() 
	{
		return new VirtualCurrencyPack[]{};
	}

	public VirtualCategory[] GetCategories() 
	{
		return new VirtualCategory[]{};
	}

	public const string PREMIUM_ID = "com.capelagames.furryfriends.premium";
	
	public static VirtualGood PREMIUM = new LifetimeVG(
			"Premium",
			"Unlock full version of the game",
			PREMIUM_ID,
			new PurchaseWithMarket(new MarketItem(PREMIUM_ID, MarketItem.Consumable.NONCONSUMABLE , 2.99))
			);
}

Thank you for the help :)

**Comment by sluzky** [comment]
@CapelaGames the recent commit should fix the issue, please let me know.
You can get the package from github master, since this fix is not yet in a stable version.

**Comment by CapelaGames** [comment]
I got it working with this fix, thank you very much

**Comment by sluzky** [comment]
@CapelaGames no problem
