### ISSUE TITLE
Unity 4.6.2 SoomlaSecret

### ISSUE THREAD

**Issue by claudiojundi** [soomla/unity3d-store#406]
I have updated to unity 4.6.2 and now when i export to Eclipse and try to build it

in log show freezes in loading.scene and show me this message

"E/Unity(9154): SOOMLA SoomlaStore You have to change SoomlaSecret !!! Stopping here !!"
I already have put the Soomla Secret on Soomla > Edit Settings. And is the same String as the older version.

My soomla package is the last one

soomla-unity3d-core v1.0.3
unity3d-store v1.7.9

and in Eclipse i have already put the 

-SoomlaAndroidCore.jar
-square-otto-1.3.2.jar
-AndroidStore.jar
-AndroidStoreGooglePlay.jar
-unity-classes.jar
-UnityAndroidStore.jar
-UnitySoomlaAndroidCore.jar

Can anyone help me?

Thanks!

**Comment by refaelos** [comment]
Can you open the SOOMLA settings panel (under Window > Soomla) and set a Soomla Password there?

**Comment by claudiojundi** [comment]
Yes! And is the same String as the older version.

**Comment by refaelos** [comment]
Do you have the StoreEvents and CoreEvents prefabs in the scene?

**Comment by claudiojundi** [comment]
Yes. I have already deleted and re-added the prefabs.

I have already changed the Soomla Secret too and continues to log 

 E/Unity(1322): SOOMLA SoomlaStore You have to change SoomlaSecret !!! Stopping here !!
 E/Unity(1322):  
 (Filename: ./artifacts/AndroidManagedGenerated/UnityEngineDebug.cpp Line: 56)

**Comment by claudiojundi** [comment]
I discovered what happened.

I have initialized my soomla in Loading.scene but i just im just using in the next scene.And my application is splitted because is higher than 50mb.Causing some error that error.

Thanks! You can close this topic
