### ISSUE TITLE
Purchases via different phone but same Google account

### ISSUE THREAD

**Issue by Incradiator** [soomla/unity3d-store#407]
Hello, 
Thiis was probably answered, but I can't seem to find it. It's not really an issue, but concerns me as a merchant. 

When you sell a you permanent item that you can only have one of,  google doesnt let you buy another one, but does buying the item using the buy item method trigger the market purchase event if you access it with a different phone? 
I'm trying to be a super fair guy and I don't believe in consumable virtual items especially if people lose their purchases simply because they accidentally cleared their data, lost their phone, upgraded it and so forth. 
Or should I save the purchases manually using cloud storage.
I know there's a response code that gets sent if the item has already been purchased, but does the SOOMLA framework receive and use this data?
sorry for raising this as an issue.

Any help will be greatly appreciated,
incradiator

**Comment by refaelos** [comment]
Can you post it at http://answers.soom.la ?
