### ISSUE TITLE
NullReferenceException when calling BuyItem from the editor

### ISSUE THREAD

**Issue by sambauwens** [soomla/unity3d-store#409]
I'm not sure I'm supposed to call BuyItem from the Unity Editor, but when I do I get a NullReferenceException [on line 332 of the StoreEvents file](https://github.com/soomla/unity3d-store/blob/afa2a42c5de80bb055ee82fb35a727549e564eda/Soomla/Assets/Plugins/Soomla/Store/StoreEvents.cs#L332).

I fixed it by replacing

```
if (eventJSON.HasField("extra")) {
	var extraJSON = eventJSON["extra"];
	foreach(string key in extraJSON.keys) {
		extra.Add(key, extraJSON[key].str);
	}
}
```

with

```
if (eventJSON.HasField("extra")) {
	var extraJSON = eventJSON["extra"];

	if (extraJSON.keys != null) {
		foreach (string key in extraJSON.keys) {
			extra.Add(key, extraJSON[key].str);
		} 
	}
}
```

Then I realised the code on the repo is different, so I tried it but it also raises a NullReferenceException:

```
if (eventJSON.HasField("extra")) {
	var extraJSON = eventJSON["extra"];
	foreach(string key in extraJSON.keys) {
		if (extraJSON[key] != null) {
			extra.Add(key, extraJSON[key].str);
		}
	}
}
```

**Comment by refaelos** [comment]
Can you pull request your fix?

**Comment by sambauwens** [comment]
Sure!

**Comment by sambauwens** [comment]
Whoops I think I just put the pull request on my fork. I edited the file directly from github and it seems to have created the pull request on my own fork, which I question the usefullness of.

**Comment by sambauwens** [comment]
Ok now it's on soomla's repo :)

**Comment by refaelos** [comment]
Got it in.
Thanks!
