### ISSUE TITLE
Soomla 1.7.11, SoomlaStore

### ISSUE THREAD

**Issue by Hsantos** [soomla/unity3d-store#411]
I have updated to Soomla  1.7.11 in my project and when i started the game shows the error:
"SoomlaStore You have to change SoomlaSecret !!! Stopping here !!"

**Comment by sluzky** [comment]
@Hsantos you have to change the soomla secret in hour soomla settings window.

**Comment by Hsantos** [comment]
@sluzky  I'm sorry, I did not.
I need to change for what? I am developing for ios

**Comment by sluzky** [comment]
@Hsantos you have to change it to your own secret string. Please follow the getting started instructions in the git's README to get you up and running.

**Comment by Hsantos** [comment]
@sluzky  I was using a key. Changed the key and it worked. 

Thank `s
