### ISSUE TITLE
Bad Magic Number

### ISSUE THREAD

**Issue by VCRhythm** [soomla/unity3d-store#414]
I'm receiving the following error for each of the four Soomla python files when building for iOS on Windows (the same project builds fine for Android):

Error: Traceback (most recent call last):
  File "Soomla\Editor\build-tools\Soomla_HighwayRunner.py", line 3, in <module>
    from mod_pbxproj import *
ImportError: Bad magic number in Soomla\Editor\build-tools\mod_pbxproj.pyc
   code: 1

What does this mean?

**Comment by refaelos** [comment]
Never got that. It looks like a problem with the build or python version.

Why are you building iOS on Windows? How will you run it on a device?

**Comment by VCRhythm** [comment]
We run Unity on Windows machines and transfer to (less powerful) iMacs for
deployment through Xcode. Admittedly not the most usual workflow. Soomla is
so awesome it may be worth getting Unity on an iMac just to make it work.

**Comment by refaelos** [comment]
First of all ... :heart_eyes:  for liking SOOMLA :) We're working hard for that.

Second, I heard about others who did succeed building on Windows. Try posting this question on http://answers.soom.la

**Comment by refaelos** [comment]
Closing this issue. Open it if you need.
