### ISSUE TITLE
I got an error when I was trying In-App..

### ISSUE THREAD

**Issue by mhhk88** [soomla/unity3d-store#415]
I got an error msg saying ...
Assets/Scripts/BuyGoldBars.cs(40,29): error CS1502: The best overloaded method match for `Soomla.Store.SoomlaStore.Initialize(Soomla.Store.IStoreAssets)' has some invalid arguments

Honestly, I don't exactly understand how Soomla works. 
Anyway, I hope I can get some help from here.  Please, someone check my codes and see if something wrong.
Here's my codes. 
-----------------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using System;
using Soomla.Store;

private string[] assetIDs = new string[4];
private int assetIdx = 0;

void Start() {
    SoomlaStore.Initialize(new MyInAppAssets());
    int i = 0;
    foreach(VirtualCurrencyPack cp in StoreInfo.CurrencyPacks) {
        assetIDs[i] = cp.ItemId;
    }
...
...

void BuyItem1() {
    try {
		StoreInventory.BuyItem(assetIDs[assetIdx]);
	} catch (Exception e) {
		// display error msg..
	} 
...
...

-------------------------------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Soomla.Store;

public class MyInAppAssets : MonoBehaviour {

	public const string GOLD_CURRENCY_ITEM_ID = "US$";

	public const string InAppId_1 = "AmazingShooter1200GoldBars";
	public const string InAppId_2 = "AmazingShooter3000GoldBars";
	public const string InAppId_3 = "AmazingShooter5000GoldBars";
	public const string InAppId_4 = "AmazingShooter10000GoldBars";

	public static VirtualCurrency MUFFIN_CURRENCY = new VirtualCurrency(
		"US$",										// name
		"US Dollar",												// description
		GOLD_CURRENCY_ITEM_ID							// item id
		);
	
	VirtualCurrencyPack GoldBars1200 = new VirtualCurrencyPack(
		"1200 Gold Bars",
		"A pack of 1,200 Gold Bars",
		InAppId_1,
		1200,
		GOLD_CURRENCY_ITEM_ID,
		new PurchaseWithMarket(InAppId_1, 0.99)
		);
	
	VirtualCurrencyPack GoldBars3000 = new VirtualCurrencyPack(
		"3000 Gold Bars",
		"A pack of 3,000 Gold Bars",
		InAppId_1,
		3000,
		GOLD_CURRENCY_ITEM_ID,
		new PurchaseWithMarket(InAppId_2, 1.99)
		);
	
	VirtualCurrencyPack GoldBars5000 = new VirtualCurrencyPack(
		"5000 Gold Bars",
		"A pack of 5,000 Gold Bars",
		InAppId_1,
		5000,
		GOLD_CURRENCY_ITEM_ID,
		new PurchaseWithMarket(InAppId_3, 2.99)
		);
	
	VirtualCurrencyPack GoldBars10000 = new VirtualCurrencyPack(
		"10000 Gold Bars",
		"A pack of 10,000 Gold Bars",
		InAppId_1,
		10000,
		GOLD_CURRENCY_ITEM_ID,
		new PurchaseWithMarket(InAppId_4, 4.99)
		);

	public static VirtualCategory GENERAL_CATEGORY = new VirtualCategory(
		"General", new List<string>(new string[] { InAppId_1, InAppId_2, InAppId_3, InAppId_4 })
		);
}

**Comment by refaelos** [comment]
You should ready a little bit about how SOOMLA works.

Try: http://know.soom.la

**Comment by mhhk88** [comment]
To Mr. Rafaelos: 
I've read the documents you mentioned. I am confused what is difference between Virtual Currency and Virtual Goods. Virtual goods is a way to buy items (not virtual currency) directly?

I'd like to ask some more questions, if you don't mind.
- I want to sell gold coins. Should I use Virtual Currency Pack?
- Do users actually pay when StoreInventory.BuyItem is perfromed ? Does Apple give any status of the transaction back to me?
- Can I have localized money (by countries) from Apple using any of your methods?
- It seems Soomla controls the inventory of currencies. But I need to do it by myself. Is that OK ?

**Comment by refaelos** [comment]
VirtualCurrency - something you use as a currency in your game. it will also be used to buy virtual goods.

* Yes. Just create a pack of how many gold coins you wanna sell.
* Yes. The purchase process starts right away. You'll get an event when a purchase starts/cancelled/finished
* Yes. Look into MarketItem and see the fields that starts with the word "market". All these fields are fetched from the market on runtime one of the is the localized price.
* You can do it by yourself but then the inventory will be held twice which is a waste. SOOMLA provide with easy to use API for accessing and manipulating the storage. Take a look at StoreInventory and StoreInfo for that.
