### ISSUE TITLE
Itunes connection error.

### ISSUE THREAD

**Issue by mhhk88** [soomla/unity3d-store#416]
I'm working on In-App process on ios. I got this error message when StoreInventory.BuyItem is performed.
SOOMLA SoomlaStore: An error occured for product id "AmazingShooter3000GoldBars" with code "0" and description "Cannot connect to iTunes Store"  Unexpected error... 

I think I did things right by manual. This msg came from onUnexpectedErrorInStore(). WIFI works well though.
What might cause this kind of error? 
Thank you in advance for your help. I've been struggling to implement in-app purchase for days. T..T

**Comment by sluzky** [comment]
Hey @mhhk88,

Are you working in a simulator?

**Comment by mhhk88** [comment]
@sluzky  No. It happened on iPod. I wonder what I missed.

**Comment by sluzky** [comment]
@mhhk88 

1. Can you open the app store ok on the device?
1. Have you setup the products on Apple's iTunes Connect?
1. We have a few [helpful iOS video tutorials](http://know.soom.la/docs/university/videos/) here which might help you check what you might have missed.

**Comment by mhhk88** [comment]
@sluzky 
Yes. 1 and 2 are OK. But I am a little confused with your program source 'MuffinRushAssets.cs'. The video and the zip file are different. Anyway...
What should I put in here 'StoreInventory.BuyItem ( ?????? )' ?
Is it supposed to be the same as the product ID in InApp that we set? I put the one.

One more thing. Can I have localized value of payment from Apple using any of your methods ?

**Comment by mhhk88** [comment]
Error msg: 
[*** ERROR ***] SOOMLA SoomlaStore: An error occured for product id "AmazingShooter1200GoldBars" with code "0" and description "iTunes Store에 연결할 수 없음"
SOOMLA StoreEvents SOOMLA/UNITY onUnexpectedErrorInStore
UnityEngine.Debug:Internal_Log(Int32, String, Object)
UnityEngine.Debug:Log(Object)
Soomla.SoomlaUtils:LogDebug(String, String)
Soomla.Store.StoreEvents:onUnexpectedErrorInStore(String, Boolean)
Soomla.Store.StoreEvents:onUnexpectedErrorInStore(String)
 
(Filename: /Applications/buildAgent/work/d63dfc6385190b60/artifacts/iPhonePlayer-armv7Generated/UnityEngineDebug.cpp Line: 49)

iTunes Store에 연결할 수 없음 --> meaning 'Cannnot connect to iTunes Store'.
Is that help?

**Comment by sluzky** [comment]
@mhhk88 ok, good to know you fixed it. can you share the solution with the community?

Anything that happens with iTunes is beyond our framework, meaning all things related to their authorization process, etc.

Regarding localized currency, with your virtual items which have a purchase type of `PurchaseWithMarket` you have a `MarketItem` there, in it you have a [`MarketPriceAndCurrency`](https://github.com/soomla/unity3d-store/blob/master/Soomla/Assets/Plugins/Soomla/Store/domain/MarketItem.cs#L56) field, which returns a localized price. Note that that field is filled only after the [`OnMarketItemsRefreshFinished `](https://github.com/soomla/unity3d-store/blob/master/Soomla/Assets/Plugins/Soomla/Store/StoreEvents.cs#L562) event

**Comment by mhhk88** [comment]
I logged off my iTunes Connect account of the test phone before I am buying an item. 
And I tried it again. iTunes asked me to enter my test account and everything goes OK.

It sounds great that you can get the localized currency. Thanks for all your help^^

**Comment by sluzky** [comment]
@mhhk88 so can I close this issue?

**Comment by mhhk88** [comment]
@sluzky Sure! Thanks!

**Comment by sluzky** [comment]
@mhhk88 no problem
