### ISSUE TITLE
PurchaseWithVirtualItem.CanAfford fails when funds are equal to purchase amount

### ISSUE THREAD

**Issue by drforgetful** [soomla/unity3d-store#418]
Hi,

Not sure if this is a bug or the intention of the design, but the "CanAfford", and subsequently the "checkTargetBalance" methods of PurchaseWithVirtualItem only returns true if the user has a greater amount of currency than the purchase price, rather than greater than or equal to. 
I've changed this in my local installation, but please let me know if this was by design and I've now broken something :)

**Comment by sluzky** [comment]
@drforgetful you are correct it was a bug, but it was fixed in v1.7.10 so please update your version.

**Comment by drforgetful** [comment]
@sluzky So sorry, didn't realise the package was out of date, should have checked that first. Thanks!

**Comment by sluzky** [comment]
@drforgetful no worries man.
