### ISSUE TITLE
Amazon In-app purchase does not seem to work

### ISSUE THREAD

**Issue by Whyser** [soomla/unity3d-store#419]
I'm using soomla-core 1.0.5 and soomla-store 1.7.12.

I've tried testing in-app purchasing using the Amazon billing, both with the use of the amazon.sdktester.json file (with App Tester) and by using Live App Testing. I don't seem to be able to fetch the SKUS. And trying to buy an item (when the fetching didnt complete) will cause the following error:

    02-24 11:46:37.964: E/SOOMLA SoomlaStore(12571): Can't proceed with launchPurchaseFlow. error: Can't start async operation (launchPurchaseFlow) because another async operation(fetch skus details) is in progress.
    02-24 11:46:37.964: E/SOOMLA SoomlaStore(12571): ERROR: SoomlaStore failure: Can't proceed with launchPurchaseFlow. error: Can't start async operation (launchPurchaseFlow) because another async operation(fetch skus details) is in progress.

**Comment by Whyser** [comment]
This issue is fixed in the next update I've been told. @sluzky Should close this and comment.

**Comment by sluzky** [comment]
@Whyser thanks for finding this.

Fixed in [v1.7.13](https://github.com/soomla/unity3d-store/commit/1338a5978f860366ee21631fd483a6498c57b42f).

**Comment by benuto** [comment]
Hey just found this post and did't want to start a new one about the same issue. I'm using core 1.0.6 and store 1.7.15 and get the same error.
