### ISSUE TITLE
Event Handling for LifeTime Virtual Good "No Ads"(Real Market Purchase)

### ISSUE THREAD

**Issue by simsis3d** [soomla/unity3d-store#420]
Hi @gurdotan @refaelos 
I have foolowed that https://www.youtube.com/watch?v=zsWVcAajMjY  video which is in fact pretty much a good tutorial for soomla. In that video, he check StoreInventory.GetItemBalance("turn_green_item_id") >= 1  for every two seconds in update cycle. However, that does not seem to me a good way. StoreEvents is good for that purpose I think.But, I couldnt figure out how to use it. I need a solution like that

public void onMarketPurchase(PurchasableVirtualItem pvi, string payload, Dictionary<string, string> extra) {
if(succes)
Do Success;
else
Do NotSucces;
}

can anyone help me with the code?

**Comment by refaelos** [comment]
onMarketPurchase means that the purchase has succeeded. There are other events for failure.

**Comment by simsis3d** [comment]
So the code will be like that? I need exact code:)

public void onMarketPurchase (PurchasableVirtualItem pvi, string payload, Dictionary<string, string> extra)
		{
			if(pvi.ItemId == "no_ads")
			{
				RemoveAds();
			}

			else
			{
				DoOtherItemPurchased();
			}
				
		}

**Comment by refaelos** [comment]
You're right.
You just need to swipe a bit through the knowledge base: http://know.soom.la/unity/store/store_events
