### ISSUE TITLE
Overwriting Default Event handlers

### ISSUE THREAD

**Issue by AliA74** [soomla/unity3d-store#421]
Hey there.

We are using Soomla to connect and buy items in our project. We have our own system for storage and we don't want to use Soomla DB approach . So we thought we can overwrite default event handlers so that will cause Soomla not to use DB anymore.
For example , instead of using :
StoreEvents.OnMarketPurchase += onMarketPurchase;

we think we can use this :
StoreEvents.OnMarketPurchase = onMarketPurchase;

Are we thinking correctly ? Will this cause any kind of problem ?

Thanks in advance.

**Comment by refaelos** [comment]
We suggest that you use SOOMLA the way it should be used. SOOMLA is a framework and not an IAP plugin. If you want just an IAP plugin you're welcome to use Prime31 or Unibill.

You should think about using SOOMLA for saving the balances. It's a very strong SDK for that and other things.
