### ISSUE TITLE
INAPP_PURCHASE_DATA and INAPP_DATA_SIGNATURE

### ISSUE THREAD

**Issue by skymanrm** [soomla/unity3d-store#423]
Hi all, i tried implement analytics to game, for verify user iap i need next parameters INAPP_PURCHASE_DATA and INAPP_DATA_SIGNATURE, i found only "extra" parameter in purchase callback and this info:
The "extra" dictionary will contain "orderId" and "purchaseToken"
But this is not enough, can you tell me where i can got required vars?

**Comment by refaelos** [comment]
It's implemented and going to be merged soon.
https://github.com/soomla/unity3d-store/pull/422

**Comment by skymanrm** [comment]
I used MobileAppTracking, it service can verify each purchase event for eliminate revenue from fraudulent purchases. Thanks for link, i will check this tool, may be we will implement it later. Anyway, i hope that you will merge this pull request soon, now i will do this self on my side. Thanks for help.

**Comment by refaelos** [comment]
Ok.

Just so you know: the link is for a service that is pretty new. If you want to get more info about it you can send an email to yaniv@soom.la
