### ISSUE TITLE
Where to download soomla unity packages?

### ISSUE THREAD

**Issue by Omegas7** [soomla/unity3d-store#425]
At https://github.com/soomla/unity3d-store it is not possible to download soomla-unity3d-core v1.0.6 or unity3d-store v1.7.15 because library.soom.la is down. Where am I supposed to download these then?

**Comment by cocojiambo** [comment]
I was having some problems downloading them yesterday as well.

**Comment by refaelos** [comment]
It should work just fine now.
Closing
