### ISSUE TITLE
No money being taken.

### ISSUE THREAD

**Issue by BCRyman** [soomla/unity3d-store#428]
Hi there,

2 things really;

1) Working on an app for a client, I have the onMarketPurchase being called and that works fine, the item is bought and my calls from that method work as expected. However it appears that despite the standard popups saying how much the item will be showing, the user isn't getting charged the money that it says. Do you have any ideas on this? This is only on iOS.

2) Upon trying to buy an item with market on android it tries to log into my google play account but fails and a popup says that authentication is required. Doing some research online suggests this hasn't got anything to do with the plugin and my implementation is fine, but just wanted to check!

Thanks!

**Comment by refaelos** [comment]
This is an outdated issue. If you still need assistance please ask on http://answers.soom.la
