### ISSUE TITLE
iOS repeated purchase has possibly-invalid receipt

### ISSUE THREAD

**Issue by tenpn** [soomla/unity3d-store#429]
If the user attempts to buy a managed product they already own on a fresh install, both itunes and Soomla allow this complete (without charging the player twice). This is good. Soomla returns a transaction ID and receipt path to the game. 

This transaction ID does not seem to match the receipt. We pass both to our server, which expands the receipt, but cannot find a matching transaction ID. It does indeed contain a purchase for the product in question, but with a different (maybe original?) transaction ID. This is bad, because we can't know that this mismatch is ok; it might be coming from a replay attack or other hack.

This isn't a problem for our other games that do not use soomla, but use the same receipt verification server. Repeated purchases return transaction IDs and receipts that match.

The same problem happens if using restore purchases instead of attempting to rebuy a product.

**Comment by refaelos** [comment]
Ok... that's a weird one. We don't do anything to mess with the receipt. The behavior you get with SOOMLA is the same as without SOOMLA (in this case).

**Comment by tenpn** [comment]
Maybe it's the transaction ID that's bad? Remember the receipt is validated by our server, and contains an IAP purchase, it's just got the wrong transaction ID. Is there any more information I could be giving you?

**Comment by refaelos** [comment]
We are just forwarding he receipt. We don't do anything else with it.

Are you using SOOMLA's receipt verification?
If yes, are you using the latest version?

**Comment by tenpn** [comment]
As I said, we're using our own server. We've just upgraded to plugin version 1.7.15 from the asset store. And like I said, it's the transaction ID, which is separate from the receipt, that might be suspect.

**Comment by refaelos** [comment]
What do you mean by transaction ID? If it's something that Apple provide so we don't deal with that. We just transform it as it is.

**Comment by tenpn** [comment]
Sorry, the dictionary that's passed with OnMarketPurchase has a token key on iOS. That's what I call a transaction ID. We take the receipt from that dictionary along with the token and expect them to match. 

The receipt you send back is a receipt for the whole app, containing all purchases. Maybe that's the problem. Our other games get a receipt for just this (re)purchase.

**Comment by refaelos** [comment]
Ok... that might be it.

Let me explain how we extract the data and maybe you can tell me how to do it differently:
1. The purchase data is being fired to an event here:  https://github.com/soomla/ios-store/blob/master/SoomlaiOSStore/SoomlaStore.m#L171
2. The actual firing of the event is here: https://github.com/soomla/ios-store/blob/master/SoomlaiOSStore/StoreEventHandling.m#L117
3. And how it's being dispatched into Unity is here: https://github.com/soomla/unity3d-store/blob/master/soomla-native/projects/unity-ios-store/SoomlaUnity/UnityStoreEventDispatcher.mm#L189

As you can see, we just take the token and the receipt and forward them. Do you have any idea how it can be done differently? Maybe something you're doing on your own is different?

**Comment by tenpn** [comment]
So I wonder if the problem is in listing 1. From what I can stackoverflow and google (http://stackoverflow.com/questions/29748866/ios-receipt-does-not-include-repurchased-transaction/29850766#29850766), you should bet returning me the transaction from `transaction. originalTransaction`. That should have the correct transaction ID.

**Comment by refaelos** [comment]
You want to add this change and pull-request it?

**Comment by refaelos** [comment]
it's on master. closing.
