### ISSUE TITLE
Multiples problems with LifeTimeVG

### ISSUE THREAD

**Issue by tspoke** [soomla/unity3d-store#430]
Hello,

First, sorry for my english, I'm french. I'll try to do my best.

I have multiples issues with soomla. Not really code-base issue, more "understand" issues. I already used Soomla in another project with Currency/CurrencyPack and all work perfectly.

I would like to implement NO_ADS LifeTimeVG in my game. It's that simple.

I code this in my IStoreAsset : 
```
public static VirtualGood NO_ADS = new LifetimeVG(
		"Remove ads",                             // Name
		"Remove ads !",                       // Description
		"remove_ads",                          // Item ID
		new PurchaseWithMarket(               // Purchase type (with real money $)
			"remove_ads",                      // Product ID
			1.20                                   // Price (in real money $)
		)
	);
```

On GooglePlay I created the item with "remove_ads" id. Everything is ok.
I was able to buy the test item with soomla on my android phone. Google Wallet got the test paiement. But events were not triggered in my game.
Now, I can't try anymore for now (I have to cancel the order on Google to try again, that's horrible).

I would like to understand how soomla really works. Because on your documentation, you list events and methods but it's a little bit complicated to really know what&when things are done.

**1 -** What is the process of this code ?
``` 
StoreInventory.BuyItem("remove_ads");
```
BuyItem => Open google service => paiement success => which event ?? (OnMarketPurchase, OnItemPurchase, OnGoodUpgrade, OnGoodBalanceChanged,.....) ? 
Which event should I listen ?

**2 -** When does Soomla retrieve status about LifeTimeVG ? **I always have a balance : 0** on my android. But, in the Unity editor, everything works perfectly.
I start **StartIabServiceInBg()** when I open the store UI. I tried to call this method at the game Start, but nothing changed. Everytime I call : **StoreInventory.GetItemBalance("remove_ads");** I got 0.

**3 -** How can I check if the player bought this item ? Should I implement my custom storage ? It sounds weird.

It could be really interesting to make a graphic/diagram listing of all methods/events orders (depending type of item) in your documentation. It could help a lot !

Thank you very much for your attention and for making Soomla !
Spoke44.

**Comment by refaelos** [comment]
1 - Information about all events can be found here: http://know-stg.soom.la/unity/store/store_events . If you still have questions after going over that document let me know.
2 - I don't understand the question. On Android, restore-transactions runs automatically when the app starts. Maybe you just forgot to add the relevant prefabs to the scene.
3 - You can check the balance of the item.

If you'd post questions to http://answers.soom.la you'll get a response much faster. I suggest you move this talk there.

**Comment by tspoke** [comment]
Hello refaelos,

After 4 days I finally found the problem with adb console & this thread : http://answers.soom.la/t/solved-signature-verification-failed/300

I was pretty sure of the API key I put in Unity, I checked it with the 5 first chars and the 5 last... but it was my other game API key...
My bad... I can't test right now, but I think with the good api key everything will work !

For info, API keys in GooglePlay look like identicals for every app under the same developer account. Soomla permits (and google play too) to buy an item even if the key is wrong, that's why I thought everything was okay. I got the payment on my wallet merchant ! 
**Why Soomla doesn't check first if keys match before asking google to proceed to the payment ?**

Thank you for your answer, and sorry for the disturb ;)

**Comment by refaelos** [comment]
How can SOOMLA check if the key matches?

**Comment by tspoke** [comment]
"The force" can !

Seriously, I just read the android IAB documentation. I thought that it was more than just an API call :)


Thanks again for your help
