### ISSUE TITLE
Leaks at initializing soomla store

### ISSUE THREAD

**Issue by dyegos** [soomla/unity3d-store#431]
I'm getting some leak in soomla initializer involving [NSString initWIthUTF8String] and [NSPlaceholderString initiWithData:encoding:]

I've profiled it in instruments and a lot of leaks showed up in the lines I initialize soomla store.

**Comment by refaelos** [comment]
Are you talking about the iOS project?
Maybe you can test it  on the native code to make sure: [ios-store](https://github.com/soomla/ios-store)

**Comment by dyegos** [comment]
I'm using C++ Soomla for cocos 2d...

**Comment by refaelos** [comment]
So why are you posting on unity3d project?

You can actually post this on http://answers.soom.la and get much quicker answers. Be prepared with some more logs or anything else you can present that shows the problem.

**Comment by dyegos** [comment]
ok, my bad
