### ISSUE TITLE
VirtualCoinPack not Cosnumed

### ISSUE THREAD

**Issue by soma-web** [soomla/unity3d-store#434]
I am trying to consume a VirtualCoinPack with the new update.

    public void BuyCoinPack(VirtualCurrencyPack pack){
       pack.Buy("SomePayload");
    }

If I want to purchase it a second Time, I get: 
    "E/SOOMLA GoogleIabHelper( 5852): Unable to buy item, Error response: 7:Item Already Owned 
     E/SOOMLA GoogleIabHelper( 5852): Can't consume coinpack_1. No token.
     UnexpectedErrorInStore : PurchaseInfo is missing token for sku: coinpack_1          PurchaseInfo(type:inapp):{"productId":coinpack_1} (response: -1007:Missing token)"

How do I consume such a item, what should be done to rebuy it?

Thanks in advance!

**Comment by UnusedNickname** [comment]
After reimporting the whole Soomla Store it works like a charm.

**Comment by refaelos** [comment]
So it works?

**Comment by refaelos** [comment]
Closing for now. Open if still relevant.
