### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LecsoBKW** [soomla/unity3d-store#435]
I have  error CS0117: `Soomla.Store.StoreInfo' does not contain a definition for `GetLifetimeVG' 

void onSoomlaStoreInitialized() {   
LifetimeVGs = StoreInfo.GetLifetimeVG();
} 

IStoreAssets file have : 
public LifetimeVG[] GetLifeTimeVG() { 
return nre LifetimeVG[]{NO_ADS_NONCONS}; 
}

what is the problem? Help

**Comment by refaelos** [comment]
My guess is that `GetLifetimeVG` is not a function of StoreInfo ....

Please post your questions to http://answers.soom.la
