### ISSUE TITLE
MissingMethodException: onMarketItemsRefreshFinished

### ISSUE THREAD

**Issue by unity-github** [soomla/unity3d-store#436]
Using the latest unity3d-core (1.0.7) and unity3d-store (1.7.16) on Windows and Android.
When running on a device, I'm getting :

```
I/Unity   (21532): MissingMethodException: The best match for method onMarketItemsRefreshFinished has some invalid parameter.
I/Unity   (21532):   at System.MonoType.InvokeMember (System.String name, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object target, System.Object[] args, System.Reflection.ParameterModifier[] modifiers, System.Globalization.CultureInfo culture, System.String[] namedParameters) [0x00
62e] in /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System/MonoType.cs:520
I/Unity   (21532):   at UnityEngine.SetupCoroutine.InvokeMember (System.Object behaviour, System.String name, System.Object variable) [0x00000] in <filename unknown>:0
```

This also happens for onRestoreTransactionsFinished, and the app locks up. It's fine running in the Unity Editor.

Is this some mismatch between versions of core and store?

**Comment by refaelos** [comment]
The versions look ok. Don't know why you're getting it...

1. Try to import SOOMLA again.
2. Ask your question on http://answers.soom.la - you'll get faster answers.

**Comment by refaelos** [comment]
The versions look ok. Don't know why you're getting it...

1. Try to import SOOMLA again.
2. Ask your question on http://answers.soom.la - you'll get faster answers.
