### ISSUE TITLE
In the .unitypackage, billing services jars are links

### ISSUE THREAD

**Issue by spl0k** [soomla/unity3d-store#450]
When importing the *soomla-unity3d-store.unitypackage*, files in *Assets/WebPlayerTemplates/SoomlaConfig/* are actually broken links.
When choosing a billing service in Soomla settings, it copies text files instead of jars (or other) in the *Plugins* folder. Building the project then results with a "*Unable to convert classes into dex format*" error.

Replacing those broken links with the actual files downloaded from the submodules fixed the issue.

**Comment by refaelos** [comment]
Are you on Windows or mac?

**Comment by spl0k** [comment]
Windows.
When importing, the contents of those files aren't what it should be, but rather a line of text representing a relative path.

**Comment by refaelos** [comment]
I'll take a look.
Also, you should really ask that in http://answers.soom.la. You'll get a much faster answer.
