### ISSUE TITLE
Missmatch between processor architecture ARM and x86

### ISSUE THREAD

**Issue by chrissoe** [soomla/unity3d-store#453]
There was a mismatch between the processor architecture of the project being built "ARM" and the processor architecture, "x86", of the implementation file "Sqlite.dll" for "Sqlite.winmd". Please choose a winmd file with an implementation file that has a processor architecture which matches the targeted processor architecture of your project.

Error caused when trying to deploy my app on a wp-device (Lumia 1520) with ARM.

x86 is working with all emulators perfectly, it's just happening when deploying on a real device.

Is there any opportunity to change the "winmd" file to be compatible with ARM?

**Comment by refaelos** [comment]
@ravalum your input here?

**Comment by ravalum** [comment]
HI @chrissoe 

Are you using the Unity plugin ? If so, in the Soomla Settings you have a check box "Run In Simulator", uncheck it and you will have the assemblies for ARM the next time you build the project.

If you are using the native wp module use these assemblies to run on device -> https://github.com/soomla/soomla-wp-core/tree/master/build/ARM

If you don't want to switch the assemblies when you switch architecture, you can add soomla-wp-core and wp-store project to your visual studio solution.
We plan to use PCL assemblies in the future to make this easier.

**Comment by chrissoe** [comment]
Alright, thanks for that ultra fast response!
Soomla is a really great solution.
