### ISSUE TITLE
Working in the editor, but in android...

### ISSUE THREAD

**Issue by narger17** [soomla/unity3d-store#454]
Hi guys, i'm using soomla for in-app purchasing,for the asset i'm using the standard one (muffin rush), and this is how i purchase : 

int temp = StoreInventory.GetItemBalance("currency_muffin");
			            try {
				           StoreInventory.BuyItem("crediti089");
			            } catch (Exception e) {
				           Debug.Log ("SOOMLA/UNITY " + e.Message);
			            }
						if(StoreInventory.GetItemBalance("currency_muffin") > temp)
				        {
						   PlayerPrefs.SetInt ("Credits",PlayerPrefs.GetInt ("Credits") + 100);
				        } 

in editor it works, but on the phone, after purchase, the PlayerPrefs.GetInt("Credits") is always the same ! what is wrong ?

**Comment by refaelos** [comment]
You'll get fast answers to your questions in: http://answers.soom.la
