### ISSUE TITLE
Can't convert classes to dex format.

### ISSUE THREAD

**Issue by syeager** [soomla/unity3d-store#459]
I am trying to make a build using Soomla with Unity 5.1.1f for Android on a Windows 7 machine. The build is failing however because it is unable to convert classes into dex format. I even tried it in an empty project with just Soomla and it still failed. Below is the error copied from the Unity Console. Thank you for your time.

CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
D:\Program Files\Java\jdk1.8.0_20\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Users/Steve/AppData/Local/Android/android-sdk\tools" -Dfile.encoding=UTF8 -jar "D:/Program Files/Unity/Editor/Data/BuildTargetTools/AndroidPlayer\sdktools.jar" -

stderr[

UNEXPECTED TOP-LEVEL EXCEPTION:
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.zip.ZipFile.<init>(ZipFile.java:164)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:244)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at SDKMain.main(SDKMain.java:129)
1 error; aborting
]
stdout[
processing archive bin\classes.jar...
processing com/unity3d/player/a$1.class...
processing com/unity3d/player/a$2.class...
processing com/unity3d/player/a$a.class...
processing com/unity3d/player/a.class...
processing com/unity3d/player/b$1.class...
processing com/unity3d/player/b$2.class...
processing com/unity3d/player/b.class...
processing com/unity3d/player/c.class...
processing com/unity3d/player/d$1.class...
processing com/unity3d/player/d$2.class...
processing com/unity3d/player/d.class...
processing com/unity3d/player/e.class...
processing com/unity3d/player/f.class...
processing com/unity3d/player/g.class...
processing com/unity3d/player/h.class...
processing com/unity3d/player/i.class...
processing com/unity3d/player/j$1.class...
processing com/unity3d/player/j$2$1$1.class...
processing com/unity3d/player/j$2$1.class...
processing com/unity3d/player/j$2.class...
processing com/unity3d/player/j.class...
processing com/unity3d/player/k$1.class...
processing com/unity3d/player/k.class...
processing com/unity3d/player/l.class...
processing com/unity3d/player/m.class...
processing com/unity3d/player/n$1.class...
processing com/unity3d/player/n.class...
processing com/unity3d/player/NativeLoader.class...
processing com/unity3d/player/o.class...
processing com/unity3d/player/ReflectionHelper$1.class...
processing com/unity3d/player/ReflectionHelper$a.class...
processing com/unity3d/player/ReflectionHelper.class...
processing com/unity3d/player/p.class...
processing com/unity3d/player/q$1.class...
processing com/unity3d/player/q$2.class...
processing com/unity3d/player/q$3.class...
processing com/unity3d/player/q.class...
processing com/unity3d/player/r.class...
processing com/unity3d/player/s.class...
processing com/unity3d/player/UnityPlayer$1.class...
processing com/unity3d/player/UnityPlayer$2.class...
processing com/unity3d/player/UnityPlayer$4.class...
processing com/unity3d/player/UnityPlayer$5.class...
processing com/unity3d/player/UnityPlayer$6.class...
processing com/unity3d/player/UnityPlayer$7.class...
processing com/unity3d/player/UnityPlayer$8.class...
processing com/unity3d/player/UnityPlayer$9.class...
processing com/unity3d/player/UnityPlayer$10.class...
processing com/unity3d/player/UnityPlayer$11.class...
processing com/unity3d/player/UnityPlayer$12.class...
processing com/unity3d/player/UnityPlayer$13$1.class...
processing com/unity3d/player/UnityPlayer$13.class...
processing com/unity3d/player/UnityPlayer$3.class...
processing com/unity3d/player/UnityPlayer$14.class...
processing com/unity3d/player/UnityPlayer$15.class...
processing com/unity3d/player/UnityPlayer$16.class...
processing com/unity3d/player/UnityPlayer$17.class...
processing com/unity3d/player/UnityPlayer$18.class...
processing com/unity3d/player/UnityPlayer$19.class...
processing com/unity3d/player/UnityPlayer$a.class...
processing com/unity3d/player/UnityPlayer$b.class...
processing com/unity3d/player/UnityPlayer$c.class...
processing com/unity3d/player/UnityPlayer.class...
processing com/unity3d/player/UnityPlayerActivity.class...
processing com/unity3d/player/UnityPlayerNativeActivity.class...
processing com/unity3d/player/UnityPlayerProxyActivity.class...
processing com/unity3d/player/t.class...
processing com/unity3d/player/u$1.class...
processing com/unity3d/player/u.class...
processing com/unity3d/player/WWW.class...
processing org/fmod/FMODAudioDevice$a.class...
processing org/fmod/FMODAudioDevice.class...
processing org/fmod/a.class...
processing bitter/jnibridge/JNIBridge$a.class...
processing bitter/jnibridge/JNIBridge.class...
processing bin\classes\.\com\google\android\gms\R$attr.class...
processing bin\classes\.\com\google\android\gms\R$color.class...
processing bin\classes\.\com\google\android\gms\R$drawable.class...
processing bin\classes\.\com\google\android\gms\R$id.class...
processing bin\classes\.\com\google\android\gms\R$integer.class...
processing bin\classes\.\com\google\android\gms\R$raw.class...
processing bin\classes\.\com\google\android\gms\R$string.class...
processing bin\classes\.\com\google\android\gms\R$style.class...
processing bin\classes\.\com\google\android\gms\R$styleable.class...
processing bin\classes\.\com\google\android\gms\R.class...
processing bin\classes\.\com\google\example\games\mainlibproj\R$attr.class...
processing bin\classes\.\com\google\example\games\mainlibproj\R$color.class...
processing bin\classes\.\com\google\example\games\mainlibproj\R$drawable.class...
processing bin\classes\.\com\google\example\games\mainlibproj\R$id.class...
processing bin\classes\.\com\google\example\games\mainlibproj\R$integer.class...
processing bin\classes\.\com\google\example\games\mainlibproj\R$raw.class...
processing bin\classes\.\com\google\example\games\mainlibproj\R$string.class...
processing bin\classes\.\com\google\example\games\mainlibproj\R$style.class...
processing bin\classes\.\com\google\example\games\mainlibproj\R$styleable.class...
processing bin\classes\.\com\google\example\games\mainlibproj\R.class...
processing bin\classes\.\com\LittleByteGames\SirPiggleton\R$attr.class...
processing bin\classes\.\com\LittleByteGames\SirPiggleton\R$color.class...
processing bin\classes\.\com\LittleByteGames\SirPiggleton\R$drawable.class...
processing bin\classes\.\com\LittleByteGames\SirPiggleton\R$id.class...
processing bin\classes\.\com\LittleByteGames\SirPiggleton\R$integer.class...
processing bin\classes\.\com\LittleByteGames\SirPiggleton\R$raw.class...
processing bin\classes\.\com\LittleByteGames\SirPiggleton\R$string.class...
processing bin\classes\.\com\LittleByteGames\SirPiggleton\R$style.class...
processing bin\classes\.\com\LittleByteGames\SirPiggleton\R$styleable.class...
processing bin\classes\.\com\LittleByteGames\SirPiggleton\R.class...
processing archive plugins\.\android-support-v4.jar...
ignored resource META-INF/MANIFEST.MF
processing android/support/v4/print/PrintHelperKitkat$1.class...
processing android/support/v4/print/PrintHelper$1.class...
processing android/support/v4/print/PrintHelper$PrintHelperVersionImpl.class...
processing android/support/v4/print/PrintHelper$PrintHelperKitkatImpl$2.class...
processing android/support/v4/print/PrintHelper$PrintHelperStubImpl.class...
processing android/support/v4/print/PrintHelperKitkat$2$1$1.class...
processing android/support/v4/print/PrintHelperKitkat$OnPrintFinishCallback.class...
processing android/support/v4/print/PrintHelper$PrintHelperKitkatImpl.class...
processing android/support/v4/print/PrintHelperKitkat$2.class...
processing android/support/v4/print/PrintHelper$OnPrintFinishCallback.class...
processing android/support/v4/print/PrintHelper$PrintHelperKitkatImpl$1.class...
processing android/support/v4/print/PrintHelperKitkat.class...
processing android/support/v4/print/PrintHelper.class...
processing android/support/v4/print/PrintHelperKitkat$2$1.class...
processing android/support/v4/animation/DonutAnimatorCompatProvider$DonutFloatValueAnimator$1.class...
processing android/support/v4/animation/HoneycombMr1AnimatorCompatProvider$HoneycombValueAnimatorCompat.class...
processing android/support/v4/animation/AnimatorUpdateListenerCompat.class...
processing android/support/v4/animation/HoneycombMr1AnimatorCompatProvider.class...
processing android/support/v4/animation/ValueAnimatorCompat.class...
processing android/support/v4/animation/AnimatorCompatHelper.class...
processing android/support/v4/animation/DonutAnimatorCompatProvider$DonutFloatValueAnimator.class...
processing android/support/v4/animation/HoneycombMr1AnimatorCompatProvider$HoneycombValueAnimatorCompat$1.class...
processing android/support/v4/animation/HoneycombMr1AnimatorCompatProvider$AnimatorListenerCompatWrapper.class...
processing android/support/v4/animation/DonutAnimatorCompatProvider.class...
processing android/support/v4/animation/AnimatorListenerCompat.class...
processing android/support/v4/animation/AnimatorProvider.class...
processing android/support/v4/view/ViewPropertyAnimatorCompatICS.class...
processing android/support/v4/view/ViewConfigurationCompat.class...
processing android/support/v4/view/MarginLayoutParamsCompat.class...
processing android/support/v4/view/MenuItemCompat$OnActionExpandListener.class...
processing android/support/v4/view/ViewPager$PageTransformer.class...
processing android/support/v4/view/NestedScrollingParent.class...
processing android/support/v4/view/GravityCompatJellybeanMr1.class...
processing android/support/v4/view/AccessibilityDelegateCompatIcs$1.class...
processing android/support/v4/view/ViewCompatHC.class...
processing android/support/v4/view/VelocityTrackerCompat$VelocityTrackerVersionImpl.class...
processing android/support/v4/view/ViewGroupCompatJellybeanMR2.class...
processing android/support/v4/view/ScaleGestureDetectorCompat$1.class...
processing android/support/v4/view/LayoutInflaterCompatHC.class...
processing android/support/v4/view/ViewPropertyAnimatorCompat$ICSViewPropertyAnimatorCompatImpl.class...
processing android/support/v4/view/ViewCompatLollipop$1.class...
processing android/support/v4/view/animation/FastOutSlowInInterpolator.class...
processing android/support/v4/view/animation/FastOutLinearInInterpolator.class...
processing android/support/v4/view/animation/PathInterpolatorCompatApi21.class...
processing android/support/v4/view/animation/LookupTableInterpolator.class...
processing android/support/v4/view/animation/PathInterpolatorDonut.class...
processing android/support/v4/view/animation/PathInterpolatorCompat.class...
processing android/support/v4/view/animation/PathInterpolatorCompatBase.class...
processing android/support/v4/view/animation/LinearOutSlowInInterpolator.class...
processing android/support/v4/view/MotionEventCompat$GingerbreadMotionEventVersionImpl.class...
processing android/support/v4/view/LayoutInflaterCompatLollipop.class...
processing android/support/v4/view/AccessibilityDelegateCompat$AccessibilityDelegateJellyBeanImpl.class...
processing android/support/v4/view/MotionEventCompatGingerbread.class...
processing android/support/v4/view/ViewPager$1.class...
processing android/support/v4/view/ViewPropertyAnimatorListener.class...
processing android/support/v4/view/ActionProvider$SubUiVisibilityListener.class...
processing android/support/v4/view/AccessibilityDelegateCompat$AccessibilityDelegateIcsImpl.class...
processing android/support/v4/view/ViewGroupCompat.class...
processing android/support/v4/view/TintableBackgroundView.class...
processing android/support/v4/view/LayoutInflaterCompat.class...
processing android/support/v4/view/PagerTitleStripIcs.class...
processing android/support/v4/view/ScaleGestureDetectorCompat$ScaleGestureDetectorCompatKitKatImpl.class...
processing android/support/v4/view/AccessibilityDelegateCompat.class...
processing android/support/v4/view/ScaleGestureDetectorCompatKitKat.class...
processing android/support/v4/view/ViewCompatGingerbread.class...
processing android/support/v4/view/ScaleGestureDetectorCompat$BaseScaleGestureDetectorImpl.class...
processing android/support/v4/view/PagerTitleStrip$PagerTitleStripImplBase.class...
processing android/support/v4/view/ViewCompat$KitKatViewCompatImpl.class...
processing android/support/v4/view/ViewGroupCompat$ViewGroupCompatJellybeanMR2Impl.class...
processing android/support/v4/view/ViewConfigurationCompatICS.class...
processing android/support/v4/view/ViewCompat$AccessibilityLiveRegion.class...
processing android/support/v4/view/WindowInsetsCompatApi21.class...
processing android/support/v4/view/NestedScrollingParentHelper.class...
processing android/support/v4/view/MenuItemCompatHoneycomb.class...
processing android/support/v4/view/InputDeviceCompat.class...
processing android/support/v4/view/MarginLayoutParamsCompatJellybeanMr1.class...
processing android/support/v4/view/ViewPropertyAnimatorCompat$1.class...
processing android/support/v4/view/ViewCompat$ImportantForAccessibility.class...
processing android/support/v4/view/KeyEventCompat.class...
processing android/support/v4/view/ViewPropertyAnimatorCompatKK$1.class...
processing android/support/v4/view/VelocityTrackerCompat$BaseVelocityTrackerVersionImpl.class...
processing android/support/v4/view/MenuCompat.class...
processing android/support/v4/view/PagerTitleStrip$PagerTitleStripImpl.class...
processing android/support/v4/view/ViewGroupCompat$ViewGroupCompatImpl.class...
processing android/support/v4/view/ViewPropertyAnimatorCompat$BaseViewPropertyAnimatorCompatImpl$Starter.class...
processing android/support/v4/view/ViewCompat$JbMr1ViewCompatImpl.class...
processing android/support/v4/view/MenuItemCompatIcs.class...
processing android/support/v4/view/ViewPager$MyAccessibilityDelegate.class...
processing android/support/v4/view/ViewPager$3.class...
processing android/support/v4/view/ViewCompatKitKat.class...
processing android/support/v4/view/MenuItemCompatIcs$OnActionExpandListenerWrapper.class...
processing android/support/v4/view/MenuItemCompatIcs$SupportActionExpandProxy.class...
processing android/support/v4/view/ViewCompatJellybeanMr1.class...
processing android/support/v4/view/LayoutInflaterCompat$LayoutInflaterCompatImplBase.class...
processing android/support/v4/view/ViewPager$LayoutParams.class...
processing android/support/v4/view/ViewCompat$BaseViewCompatImpl.class...
processing android/support/v4/view/ViewPager$SimpleOnPageChangeListener.class...
processing android/support/v4/view/GestureDetectorCompat$GestureDetectorCompatImpl.class...
processing android/support/v4/view/PagerTitleStripIcs$SingleLineAllCapsTransform.class...
processing android/support/v4/view/LayoutInflaterCompat$LayoutInflaterCompatImplV11.class...
processing android/support/v4/view/LayoutInflaterCompatBase$FactoryWrapper.class...
processing android/support/v4/view/WindowCompat.class...
processing android/support/v4/view/ViewParentCompat$ViewParentCompatKitKatImpl.class...
processing android/support/v4/view/MenuItemCompat$BaseMenuVersionImpl.class...
processing android/support/v4/view/MotionEventCompat$EclairMotionEventVersionImpl.class...
processing android/support/v4/view/PagerTitleStrip$PageListener.class...
processing android/support/v4/view/AccessibilityDelegateCompatJellyBean.class...
processing android/support/v4/view/ViewPager$OnAdapterChangeListener.class...
processing android/support/v4/view/ScaleGestureDetectorCompat$ScaleGestureDetectorImpl.class...
processing android/support/v4/view/OnApplyWindowInsetsListener.class...
processing android/support/v4/view/AccessibilityDelegateC<message truncated>

**Comment by kimshako** [comment]
http://blog.soom.la/2015/07/soomla-upgrading-made-easy.html

If you imported the new version 1.8 without removing the old version, that message will come.
Remove the previous version according to the blog posting, and import the new package.

You have to input the SOOMLA secret etc. again.

**Comment by syeager** [comment]
I have never installed any version other than 1.8. However I did try all 3 of these solutions and none of them worked. I actually can't even build without Soomla in my project anymore. It was building fine before I added Soomla a couple of times and tried all of those solutions.

**Comment by syeager** [comment]
Actually I fixed building without Soomla. I needed to remove the Package Uninstaller that was suggested in that blog post.

**Comment by syeager** [comment]
I updated Unity to 5.1.1p4 and tried installing Soomla again without success. However I did get these errors when updating the package to Unity 5.

Error importing folder (The pathName assets/plugins is already mapped to fce8a713f1e5a4cc4b9973d1ef630f31. But the meta data wants it to be mapped to b496c7f41dc144786ac71c6134876515)

Error importing folder (The pathName assets/plugins/android is already mapped to b8f0d9a6a7f9240c981894807effddbc. But the meta data wants it to be mapped to 3a716cacc82344cfc9844350b78f25ae)

**Comment by refaelos** [comment]
@syeager you should really ask your questions on http://answers.soom.la. All the experts are there ;)

**Comment by syeager** [comment]
Thanks! Sorry if this was the incorrect place to post.

**Comment by refaelos** [comment]
No that's fine. We sometimes look here as well. It's just for your benefit :)

**Comment by awatamiracle** [comment]
I have had the same error, and solved it.
If you imported both 'soomla store' and 'soomla profile', try blow.

1.  Remove all related files.
2. Import 'soomla store' from Asset Store.
3. Import 'soomla profile' from Github.

I successfully build by this.
(I don't know why)
