### ISSUE TITLE
Virtual Currency not handled correctly

### ISSUE THREAD

**Issue by PulkitSethi1984** [soomla/unity3d-store#463]
If I try to purchase a virtual items worth 50 coins, and if only 50 coins are available then I am unable to buy them. It checks ( availableCoins > requiredCoins) instead of (availableCoins >= requiredCoins).
Boundary condition is not correct

**Comment by refaelos** [comment]
Do you want to fix it and PR your changes?

**Comment by PulkitSethi1984** [comment]
Yes I will do it today.

Regards,
Pulkit

**Comment by refaelos** [comment]
:+1:

**Comment by PulkitSethi1984** [comment]
Already fixed. I have code a week before of the fix. Is duplicate. Would pick another
