### ISSUE TITLE
CommandInvokationFailure

### ISSUE THREAD

**Issue by Soolan** [soomla/unity3d-store#466]
Hi there,
Under Android Settings>Billing Srvice Selection if I choose anything other than Google Play it builds the apk file without any problem.
But when I choose Google Play I get CommandInvokationFailure

I tried reimporting the package, clearing the duplicate .jar files etc.
but the ptoblem still exists.
Thanks

P.S
I'm using the latest version of Soomla (Grow) and Unity 4.6.2

**Comment by refaelos** [comment]
can you post this question to http://answers.soom.la (also post some logs there)

**Comment by Soolan** [comment]
Sure... thanks Rafael.
