### ISSUE TITLE
How to distinguish between 2 event market item purchased and query item purchased ?

### ISSUE THREAD

**Issue by tnbao91** [soomla/unity3d-store#471]
This is first time I use Soomla so I have a little confused. I have a Non-consumable item, when I buy it successfully onMarketPurchase event is triggered. Then I uninstall my game and reinstall it, onMarketPurchase also triggered on game started. It make me crazy because I have 2 difference ways to implement result for both events

I used to use OpenIAP plugin before and they have 2 events handle it
+ purchaseSucceededEvent return succeeded purchased item 
+ queryInventorySucceededEvent return list item Non-consumable purchased

So anyone know how to handle 2 type event above in Soomla please guide me

Thank in advance

**Comment by refaelos** [comment]
You should ask this question in the SOOMLA forums at: http://answers.soom.la
