### ISSUE TITLE
Unity 5 iOs build error

### ISSUE THREAD

**Issue by ToborYag** [soomla/unity3d-store#478]
I posted this an answers, figured I would post here as well.
So my mobile app has the store integrated for Android and windows, both of which are working. When I try to build on iOS, I get the following error.
Undefined symbols for architecture armv7:
  "Soom_AutonomousStringCopy(char const*)", referenced from:
      _vgStorage_GetCurrentUpgrade in libUnityiOSStore.a(UnityVirtualGoodStorage.o)
  "_OBJC_METACLASS_$_Reward", referenced from:
      _OBJC_METACLASS_$_VirtualItemReward in libSoomlaIOSStore.a(VirtualItemReward.o)
  "_OBJC_METACLASS_$_SoomlaEntity", referenced from:
      _OBJC_METACLASS_$_VirtualItem in libSoomlaIOSStore.a(VirtualItem.o)
  "_SOOM_CLASSNAME", referenced from:
      -[MarketItem toDictionary] in libSoomlaIOSStore.a(MarketItem.o)
      -[VirtualCategory toDictionary] in libSoomlaIOSStore.a(VirtualCategory.o)
  "_keyValStorage_SetValue", referenced from:
      RegisterMonoModules() in RegisterMonoModules.o
  "_soomlaCore_Init", referenced from:
      RegisterMonoModules() in RegisterMonoModules.o
  "_OBJC_CLASS_$_KeyValueStorage", referenced from:
      objc-class-ref in libSoomlaIOSStore.a(StoreInfo.o)
      objc-class-ref in libSoomlaIOSStore.a(VirtualGoodStorage.o)
      objc-class-ref in libSoomlaIOSStore.a(StoreInventory.o)
      objc-class-ref in libSoomlaIOSStore.a(VirtualItemStorage.o)
  "_OBJC_CLASS_$_SoomlaUtils", referenced from:
      objc-class-ref in libUnityiOSStore.a(UnityStoreEventDispatcher.o)
      objc-class-ref in libSoomlaIOSStore.a(StoreInfo.o)
      objc-class-ref in libSoomlaIOSStore.a(VirtualGoodStorage.o)
      objc-class-ref in libSoomlaIOSStore.a(MarketItem.o)
      objc-class-ref in libSoomlaIOSStore.a(PurchasableVirtualItem.o)
      objc-class-ref in libSoomlaIOSStore.a(VirtualCategory.o)
      objc-class-ref in libSoomlaIOSStore.a(UpgradeVG.o)
      ...
  "_OBJC_CLASS_$_Reward", referenced from:
      _OBJC_CLASS_$_VirtualItemReward in libSoomlaIOSStore.a(VirtualItemReward.o)
  "_rewardStorage_SetTimesGiven", referenced from:
      RegisterMonoModules() in RegisterMonoModules.o
  "_rewardStorage_GetTimesGiven", referenced from:
      RegisterMonoModules() in RegisterMonoModules.o
  "_rewardStorage_GetLastSeqIdxGiven", referenced from:
      RegisterMonoModules() in RegisterMonoModules.o
  "_OBJC_CLASS_$_SoomlaEntity", referenced from:
      _OBJC_CLASS_$_VirtualItem in libSoomlaIOSStore.a(VirtualItem.o)
  "_rewardStorage_SetLastSeqIdxGiven", referenced from:
      RegisterMonoModules() in RegisterMonoModules.o
  "_rewardStorage_GetLastGivenTimeMillis", referenced from:
      RegisterMonoModules() in RegisterMonoModules.o
  "_keyValStorage_GetValue", referenced from:
      RegisterMonoModules() in RegisterMonoModules.o
  "_keyValStorage_DeleteKeyValue", referenced from:
      RegisterMonoModules() in RegisterMonoModules.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
I followed all the tutorials and reviewed several forum posts and tried several of the solutions for similar issues.
I have unity set to the default build settings, I also tried adjusting those based on posts in the forums.
I removed soomla to ensure it is what in fact is causing the error, my app builds fine without soomla.

I am currently on core version 1.0.8 and store version 1.8.1. Unity version 5.1.2f1, xcode 6.4

Any insight would be greatly appreciated.

**Comment by refaelos** [comment]
no need to post twice. closing this one.
