### ISSUE TITLE
There doesn't seem to be a nice way to actual get the category for use with GetEquippedVirtualGood

### ISSUE THREAD

**Issue by prodigga** [soomla/unity3d-store#479]
Right now, to use StoreInventory.GetEquippedVirtualGood, I have to iterate StoreInfo.Categories, find the correct category, pass it to the method. This is cumbersome compared to the other parts of the API.

For example, when interacting with virtual goods, I can just pass the ID to the various methods:

```
    StoreInventory.CanAfford(StoreAssets.CAR_1.ItemId);
    StoreInventory.BuyItem(StoreAssets.CAR_1.ItemId);
```

etc

But, for StoreInventory.GetEquippedVirtualGood, I can't reuse the static Category objects that I have defined in StoreAssets, because the Category objects inside of the store are not the same objects to the ones in the static class. (This is expected, as Soomla will deserialize the categories from its database, so the categories will be a carbon copy of your static category objects, but point to different objects).

To check which car the user has equipped in my game, I cant do this:

```
    StoreInventory.GetEquippedVirtualGood(StoreAssets.CAR_CATEGORY) //won't work
```

I have to do this:

```
    VirtualCategory found = null;
    foreach (VirtualCategory category in StoreInfo.Categories)
    {
        if (category.Name == StoreAssets.CAR_CATEGORY.Name)
        {
            found = category;
            break;
        }
    }

    StoreInventory.GetEquippedVirtualGood(found);
```

It would be nice if StoreInventory.GetEquippedVirtualGood accepted a string instead of a VirtualCategory, similar to how everything expects a goods/etc ID string, maybe comparing names or a new ID parameter for VirtualCategory?

**Comment by prodigga** [comment]
Maybe this, in the StoreInventory class?


        /// <summary>
        /// Checks currently equipped good in given <c>category</c>
        /// </summary>
        /// <param name="string">Name of the category we want to check</param>
        /// <returns>EquippableVG otherwise null</returns>
	    public static EquippableVG GetEquippedVirtualGood(string categoryName)
        {
            foreach (VirtualCategory category in StoreInfo.Categories)
            {
                if (category.Name == categoryName)
                {
                    return GetEquippedVirtualGood(category);
                }
            }

            SoomlaUtils.LogError(TAG, "There is no category names " + categoryName);
            return null;
        }

**Comment by refaelos** [comment]
Is this a feature request or an issue?
If it's a feature request we'll be happy to have it PR'd into the repo.
If not, you better post it on http://answers.soom.la

**Comment by prodigga** [comment]
Feature request I suppose. I'll submit a PR, never done one before though
so bare with me haha.

**Comment by refaelos** [comment]
sure ::)
