### ISSUE TITLE
Error with SoomlaStore.BuyMarketItem

### ISSUE THREAD

**Issue by tsx5000** [soomla/unity3d-store#490]
I have just one IAP item in my store to remove ads.
My Store gets initialized correctly, but when i try to make a purchase, it throws an error
Here is my Implementation of IStore Assets : 

<code>
using UnityEngine;
using System.Collections;
using Soomla;
using Soomla.Store;

public class MarketItems : IStoreAssets 
{
	public const string REMOVE_ADS = "remove_ads";

	public static VirtualGood NO_ADS_PRODUCT = new LifetimeVG(
		"Remove Ads", 													// name
		"Stop showing all Ads",				 							// description
		"NoAds",														// item id
		new PurchaseWithMarket(REMOVE_ADS, 0.99));
	
	public int GetVersion ()
	{
		return 0;
	}
	public VirtualCurrency[] GetCurrencies ()
	{
		return new VirtualCurrency[]{};
	}
	public VirtualGood[] GetGoods ()
	{
		return new VirtualGood[]{NO_ADS_PRODUCT};
	}
	public VirtualCurrencyPack[] GetCurrencyPacks ()
	{
		return new VirtualCurrencyPack[]{};
	}
	public VirtualCategory[] GetCategories ()
	{
		return new VirtualCategory[]{};
	}
}
</code>

And my IAP handler

<code>
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Soomla;
using Soomla.Store;

public class IAPManager : MonoBehaviour 
{
	private bool showAds = true;
	public bool ShowAds
	{
		get
		{
			return showAds;
		}
	}

	private static IAPManager mInstance;
	public static IAPManager Instance
	{
		get
		{
			if(mInstance == null)
			{
				mInstance = FindObjectOfType<IAPManager>();
			}
			
			return mInstance;
		}
	}

	void Awake()
	{
		StoreEvents.OnSoomlaStoreInitialized += onInit;
		StoreEvents.OnMarketPurchase += onMarketPurchase;
		StoreEvents.OnMarketPurchaseCancelled += onMarketPurchaseCancelled;
		StoreEvents.OnUnexpectedStoreError += onStoreError;
		StoreEvents.OnBillingNotSupported += onBillingNotSupported;
		StoreEvents.OnBillingSupported += onBillingSupported;
	}

	void Start ()
	{
		Soomla.Store.SoomlaStore.Initialize (new MarketItems());
	}

	public void RemoveAds()
	{
		if(StoreInventory.GetItemBalance (MarketItems.NO_ADS_PRODUCT.ItemId) == 0)
		{
			SoomlaStore.BuyMarketItem(MarketItems.NO_ADS_PRODUCT.ItemId, "Ads Removed");
		}
		else
			Debug.Log ("Item already purchased");
	}

	public void onStoreError(int errorCode) 
	{
		SoomlaUtils.LogError ("StoreError", "error with code: " + errorCode);
	}

	public void onMarketPurchase(PurchasableVirtualItem pvi, string payload, Dictionary<string, string> extra) 
	{
		if(pvi.ItemId == MarketItems.NO_ADS_PRODUCT.ItemId)
		{
			Debug.Log ("Ads removed sucessfully");
			showAds = false;
		}
	}

		public void onMarketPurchaseCancelled(PurchasableVirtualItem pvi)
	{
		Debug.Log ("Purchase Cancelled");
	}

	public void onInit() 
	{
		if(StoreInventory.GetItemBalance (MarketItems.NO_ADS_PRODUCT.ItemId) == 0)
		{
			showAds = true;
		}
		else
			showAds = false;

		Debug.Log ("Soomla Store Init success");
	}

	public void onBillingNotSupported(){
		Debug.LogError("###@@@ Soomla OnBillingNotSupported");
	}
	public void onBillingSupported(){
		Debug.Log("###@@@ Soomla OnBillingSupported");
	}
}
</code>

The error is thrown when i call the "Remove Ads" method from a UI button.
This is the error : 
AndroidJavaException: com.soomla.store.exceptions.VirtualItemNotFoundException: Virtual item was not found when searching with productId=NoAds

Any help on this ?

**Comment by xuanll** [comment]
Soomla.Store.SoomlaStore.BuyMarketItem(IOSAppStoreAssets.GEMPACK_70_PRODUCT_ID,"ios@70");

You should use **PRODUCT_ID** in BuyMarketItem method!!!

^_^

**Comment by xuanll** [comment]
if you need to use itemId, use  **Soomla.Store.StoreInventory.BuyItem** please
```
Soomla.Store.StoreInventory.BuyItem(IOSAppStoreAssets.GEMPACK_350.ItemId, "ios@350"); 
```

**Comment by borisspektor** [comment]
@tsx5000 does this help?

I am closing this ticket. If you have further issues please post them at http://answers.soom.la for a faster response.
