### ISSUE TITLE
"Failed to run assembly converter" on Windows Phone 8

### ISSUE THREAD

**Issue by AlexanderSilvaB** [soomla/unity3d-store#496]
Hello,
I'm trying to compile my game for WP8 but I always get an error after the "Postprocessing Player" message from Unity. For Android and IOS it compile with success. My game uses Sqlite to other plugins so I thought that was the problem and then I create a new project and added just soomla in it and surprisingly I get the same error. The error says that the file for sqlite was not found so I tried to add manually in the StagingArea with no success. I don't know what more to do.
Do you know if it's a known issue or have seen it before and know how to solve?
I'm pasting the error message below.
Thank you very much.

Exception: Failed to run assembly converter with command line -platform=wp80 "Temp/StagingArea\Assembly-CSharp-firstpass.dll" "Temp/StagingArea\Assembly-CSharp.dll" "Temp/StagingArea\UnityEngine.dll" "Temp/StagingArea\UnityEngine.UI.dll" "Temp/StagingArea\WinRTLegacy.dll" "Temp/StagingArea\soomla-wp-core.dll" "Temp/StagingArea\wp-store.dll".
System.IO.FileNotFoundException: Assembly "Sqlite, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null" file not found.
   em Unity.PlatformAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   em Unity.PlatformAssemblyResolver.Resolve(AssemblyNameReference name)
   em Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   em Mono.Cecil.TypeReference.Resolve()
   em Unity.MetadataContainer.ResolveType(TypeReference type)
   em Unity.MetadataContainer.GetAssemblyForType(TypeReference type)
   em Unity.AssemblyWrapper.CreateMethodWrapper(MetadataContainer metadata, TypeWrapper typeWrapper, MethodDefinition method)
   em Unity.AssemblyWrapper.GetCallableMethods(TypeWrapper typeWrapper, TypeDefinition type, Boolean publicOnly)
   em Unity.AssemblyWrapper.AddType(TypeReference type)
   em Unity.GetTypesStep.Visit(TypeDefinition type)
   em Unity.TypeDefinitionDispatcher.DispatchType(TypeDefinition type)
   em Unity.TypeDefinitionDispatcher..ctor(ModuleDefinition module, ITypeDefinitionVisitor visitor)
   em Unity.GetTypesStep.ProcessModule()
   em Unity.ModuleStep.Execute()
   em Unity.Step.Execute(OperationContext operationContext, IStepContext previousStepContext)
   em Unity.Operation.Execute()
   em Unity.Program.Main(String[] args)

PostProcessWP8Player.ConvertAssemblies (System.String stagingArea, System.String playerPackage, .LibraryCollection libraries) (at C:/buildslave/unity/build/PlatformDependent/WP8Player/Extensions/Managed/PostProcessWP8Player.cs:351)
PostProcessWP8Player.PostProcess (BuildTarget target, BuildOptions options, System.String installPath, System.String stagingArea, System.String playerPackage, System.String companyName, System.String productName, Guid productGUID) (at C:/buildslave/unity/build/PlatformDependent/WP8Player/Extensions/Managed/PostProcessWP8Player.cs:213)
UnityEditor.WP8.BuildPostprocessor.PostProcess (BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/WP8Player/Extensions/Managed/ExtensionModule.cs:103)
UnityEditor.PostprocessBuildPlayer.Postprocess (BuildTarget target, System.String installPath, System.String companyName, System.String productName, Int32 width, Int32 height, System.String downloadWebplayerUrl, System.String manualDownloadWebplayerUrl, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:316)
UnityEditor.HostView:OnGUI()

**Comment by borisspektor** [comment]
@AlexanderSilvaB It would be best for you to ask this on http://answers.soom.la ... you'll get a faster answer.
