### ISSUE TITLE
"Cannot connect to iTunes Store" STUCK SUPER STUCK PLEASE HELP !!! 

### ISSUE THREAD

**Issue by divAxe24** [soomla/unity3d-store#503]
Hi,
I am stuck at this bug 
Invalid product id (when trying to fetch item details): com.gravygaming.quizjam.test008
Expecting 5 products but only fetched 0 from iTunes Store

and when I try to buy I get 
jam.test008" with code "0" and description "Error Domain=SKErrorDomain Code=0 "Cannot connect to iTunes Store" UserInfo=0x1872b950 {NSLocalizedDescription=Cannot connect to iTunes Store}"
ExampleEventHandler error with code: 3

I have tried EVERYTHING :(

deleting the app and trying again, 
using sandbox test users, 
creating new sandbox test users and use them, 
double checked that the product id's match
double checked that the bundle id's match
setup inapps in itunes account MANY times
increased the version number in istoreassets script

I did all the above BUT I just keep getting this error, I have been following posts and tried everything mentioned but the error just wont go away. PLEASE HELP ME !!!

this is the log

2015-11-30 10:11:39.368 quizjam[686:60b] -> registered mono modules 0x1532c60
-> applicationDidFinishLaunching()
Mono path[0] = '/var/mobile/Applications/0467A59C-8A38-46A9-A4EE-3D5EEF32DA76/quizjam.app/Data/Managed'
Mono config path = '/var/mobile/Applications/0467A59C-8A38-46A9-A4EE-3D5EEF32DA76/quizjam.app/Data/Managed'
-> applicationDidBecomeActive()
Requesting Resolution: 640x1136
Renderer: PowerVR SGX 543
Vendor:   Imagination Technologies
Version:  OpenGL ES 2.0 IMGSGX543-97.7
GL_OES_depth_texture GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_vertex_array_object GL_EXT_blend_minmax GL_EXT_color_buffer_half_float GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_draw_instanced GL_EXT_instanced_arrays GL_EXT_map_buffer_range GL_EXT_occlusion_query_boolean GL_EXT_pvrtc_sRGB GL_EXT_read_format_bgra GL_EXT_separate_shader_objects GL_EXT_shader_framebuffer_fetch GL_EXT_shader_texture_lod GL_EXT_shadow_samplers GL_EXT_sRGB GL_EXT_texture_filter_anisotropic GL_EXT_texture_rg GL_EXT_texture_storage GL_APPLE_copy_texture_levels GL_APPLE_framebuffer_multisample GL_APPLE_rgb_422 GL_APPLE_sync GL_APPLE_texture_format_BGRA8888 GL_APPLE_texture_max_level GL_IMG_read_format GL_IMG_texture_compression_pvrtc 
Creating OpenGLES2.0 graphics device
Initialize engine version: 4.6.6f2 (ab0b38d96363)
Begin MonoManager ReloadAssembly
Platform assembly: /var/mobile/Applications/0467A59C-8A38-46A9-A4EE-3D5EEF32DA76/quizjam.app/Data/Managed/UnityEngine.dll (this message is harmless)
Loading /var/mobile/Applications/0467A59C-8A38-46A9-A4EE-3D5EEF32DA76/quizjam.app/Data/Managed/UnityEngine.dll into Unity Child Domain
Non platform assembly: /private/var/mobile/Applications/0467A59C-8A38-46A9-A4EE-3D5EEF32DA76/quizjam.app/Data/Managed/System.dll (this message is harmless)
Non platform assembly: /private/var/mobile/Applications/0467A59C-8A38-46A9-A4EE-3D5EEF32DA76/quizjam.app/Data/Managed/Mono.Security.dll (this message is harmless)
Platform assembly: /var/mobile/Applications/0467A59C-8A38-46A9-A4EE-3D5EEF32DA76/quizjam.app/Data/Managed/Assembly-CSharp-firstpass.dll (this message is harmless)
Loading /var/mobile/Applications/0467A59C-8A38-46A9-A4EE-3D5EEF32DA76/quizjam.app/Data/Managed/Assembly-CSharp-firstpass.dll into Unity Child Domain
Non platform assembly: /private/var/mobile/Applications/0467A59C-8A38-46A9-A4EE-3D5EEF32DA76/quizjam.app/Data/Managed/System.Core.dll (this message is harmless)
Platform assembly: /var/mobile/Applications/0467A59C-8A38-46A9-A4EE-3D5EEF32DA76/quizjam.app/Data/Managed/Assembly-CSharp.dll (this message is harmless)
Loading /var/mobile/Applications/0467A59C-8A38-46A9-A4EE-3D5EEF32DA76/quizjam.app/Data/Managed/Assembly-CSharp.dll into Unity Child Domain
Platform assembly: /var/mobile/Applications/0467A59C-8A38-46A9-A4EE-3D5EEF32DA76/quizjam.app/Data/Managed/UnityEngine.UI.dll (this message is harmless)
Loading /var/mobile/Applications/0467A59C-8A38-46A9-A4EE-3D5EEF32DA76/quizjam.app/Data/Managed/UnityEngine.UI.dll into Unity Child Domain
Platform assembly: /var/mobile/Applications/0467A59C-8A38-46A9-A4EE-3D5EEF32DA76/quizjam.app/Data/Managed/soomla-wp-core.dll (this message is harmless)
Loading /var/mobile/Applications/0467A59C-8A38-46A9-A4EE-3D5EEF32DA76/quizjam.app/Data/Managed/soomla-wp-core.dll into Unity Child Domain
Platform assembly: /var/mobile/Applications/0467A59C-8A38-46A9-A4EE-3D5EEF32DA76/quizjam.app/Data/Managed/wp-store.dll (this message is harmless)
Loading /var/mobile/Applications/0467A59C-8A38-46A9-A4EE-3D5EEF32DA76/quizjam.app/Data/Managed/wp-store.dll into Unity Child Domain
- Completed reload, in  0.088 seconds
2015-11-30 10:11:45.980 quizjam[686:60b] [*** ERROR ***] SOOMLA SoomlaStore: Invalid product id (when trying to fetch item details): android.test.purchased
2015-11-30 10:11:45.981 quizjam[686:60b] [*** ERROR ***] SOOMLA SoomlaStore: Invalid product id (when trying to fetch item details): com.gravygaming.quizjam.test008
2015-11-30 10:11:45.982 quizjam[686:60b] [*** ERROR ***] SOOMLA SoomlaStore: Invalid product id (when trying to fetch item details): no_ads
2015-11-30 10:11:45.983 quizjam[686:60b] [*** ERROR ***] SOOMLA SoomlaStore: Invalid product id (when trying to fetch item details): 2500_pack
2015-11-30 10:11:45.985 quizjam[686:60b] [*** ERROR ***] SOOMLA SoomlaStore: Invalid product id (when trying to fetch item details): android.test.canceled
2015-11-30 10:11:45.986 quizjam[686:60b] [*** ERROR ***] SOOMLA SoomlaStore: Expecting 5 products but only fetched 0 from iTunes Store
SOOMLA/UNITY Wants to buy: 10 Muffins
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7Generated/UnityEngineDebug.cpp Line: 56)

-> applicationWillResignActive()
-> applicationDidBecomeActive()
2015-11-30 10:26:14.678 quizjam[686:60b] [*** ERROR ***] SOOMLA SoomlaStore: An error occured for product id "com.gravygaming.quizjam.test008" with code "0" and description "Error Domain=SKErrorDomain Code=0 "Cannot connect to iTunes Store" UserInfo=0x1872b950 {NSLocalizedDescription=Cannot connect to iTunes Store}"
ExampleEventHandler error with code: 3
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/iPhonePlayer-armv7Generated/UnityEngineDebug.cpp Line: 56)

**Comment by refaelos** [comment]
@divAxe24 you'll get a much faster response on http://answers.soom.la

**Comment by divAxe24** [comment]
ok I'll post it there then, thanks
