### ISSUE TITLE
`git clone ...` command fails with `Permission denied (publickey)`

### ISSUE THREAD

**Issue by p-i-** [soomla/unity3d-store#506]
The readme.md says to execute: `git clone --recursive https://github.com/soomla/unity3d-store.git`

However, this command fails to complete:

	 pi@piBookAir.local ~ /Users/pi/Dev/Unity/Shared/other/SoomLa_dec2015:
	 ⤐  git clone --recursive https://github.com/soomla/unity3d-store.git
	Cloning into 'unity3d-store'...
	remote: Counting objects: 9624, done.
	remote: Compressing objects: 100% (10/10), done.
	remote: Total 9624 (delta 2), reused 0 (delta 0), pack-reused 9614
	Receiving objects: 100% (9624/9624), 194.74 MiB | 1.12 MiB/s, done.
	Resolving deltas: 100% (5436/5436), done.
	Checking connectivity... done.
	Submodule 'submodules/android-store' (https://github.com/soomla/android-store) registered for path 'submodules/android-store'
	Submodule 'submodules/android-store-amazon' (https://github.com/soomla/android-store-amazon) registered for path 'submodules/android-store-amazon'
	Submodule 'submodules/android-store-google-play' (https://github.com/soomla/android-store-google-play) registered for path 'submodules/android-store-google-play'
	Submodule 'submodules/ios-store' (https://github.com/soomla/ios-store) registered for path 'submodules/ios-store'
	Submodule 'submodules/soomla-unity3d-core' (https://github.com/soomla/soomla-unity3d-core) registered for path 'submodules/soomla-unity3d-core'
	Submodule 'submodules/wp-store' (https://github.com/soomla/wp-store) registered for path 'submodules/wp-store'
	Cloning into 'submodules/android-store'...
	remote: Counting objects: 9020, done.
	remote: Total 9020 (delta 0), reused 0 (delta 0), pack-reused 9020
	Receiving objects: 100% (9020/9020), 19.19 MiB | 738.00 KiB/s, done.
	Resolving deltas: 100% (4660/4660), done.
	Checking connectivity... done.
	Submodule path 'submodules/android-store': checked out 'd3dc936f367bc2027235997383c8ba7f7d912a44'
	Submodule 'submodules/soomla-android-core' (https://github.com/soomla/soomla-android-core.git) registered for path 'submodules/soomla-android-core'
	Cloning into 'submodules/soomla-android-core'...
	remote: Counting objects: 763, done.
	remote: Total 763 (delta 0), reused 0 (delta 0), pack-reused 763
	Receiving objects: 100% (763/763), 682.69 KiB | 345.00 KiB/s, done.
	Resolving deltas: 100% (402/402), done.
	Checking connectivity... done.
	Submodule path 'submodules/android-store/submodules/soomla-android-core': checked out 'fb834e77235a545b2c56f5aa308401b853a541e2'
	Cloning into 'submodules/android-store-amazon'...
	remote: Counting objects: 307, done.
	remote: Total 307 (delta 0), reused 0 (delta 0), pack-reused 307
	Receiving objects: 100% (307/307), 980.97 KiB | 941.00 KiB/s, done.
	Resolving deltas: 100% (108/108), done.
	Checking connectivity... done.
	Submodule path 'submodules/android-store-amazon': checked out 'af60a732a206a8889e3d6614841db0bdea5e87b0'
	Cloning into 'submodules/android-store-google-play'...
	remote: Counting objects: 748, done.
	remote: Compressing objects: 100% (4/4), done.
	remote: Total 748 (delta 0), reused 0 (delta 0), pack-reused 744
	Receiving objects: 100% (748/748), 1.38 MiB | 651.00 KiB/s, done.
	Resolving deltas: 100% (256/256), done.
	Checking connectivity... done.
	Submodule path 'submodules/android-store-google-play': checked out 'ba944600d21897571dfaa14012535b5f30f53586'
	Cloning into 'submodules/ios-store'...
	remote: Counting objects: 3772, done.
	remote: Total 3772 (delta 0), reused 0 (delta 0), pack-reused 3772
	Receiving objects: 100% (3772/3772), 35.58 MiB | 849.00 KiB/s, done.
	Resolving deltas: 100% (2285/2285), done.
	Checking connectivity... done.
	Submodule path 'submodules/ios-store': checked out '30b76b46237863b530454adcb2169def607fbc47'
	Submodule 'submodules/soomla-ios-core' (https://github.com/soomla/soomla-ios-core.git) registered for path 'submodules/soomla-ios-core'
	Cloning into 'submodules/soomla-ios-core'...
	remote: Counting objects: 865, done.
	remote: Total 865 (delta 0), reused 0 (delta 0), pack-reused 865
	Receiving objects: 100% (865/865), 3.78 MiB | 827.00 KiB/s, done.
	Resolving deltas: 100% (531/531), done.
	Checking connectivity... done.
	Submodule path 'submodules/ios-store/submodules/soomla-ios-core': checked out 'edf51c9769e8b3583dd28d0de6c774c4f20a0d87'
	Cloning into 'submodules/soomla-unity3d-core'...
	remote: Counting objects: 2999, done.
	remote: Compressing objects: 100% (7/7), done.
	remote: Total 2999 (delta 1), reused 0 (delta 0), pack-reused 2992
	Receiving objects: 100% (2999/2999), 20.93 MiB | 818.00 KiB/s, done.
	Resolving deltas: 100% (1503/1503), done.
	Checking connectivity... done.
	Submodule path 'submodules/soomla-unity3d-core': checked out '89096e74a40b5f4128c54e1e213317ac10d8c962'
	Submodule 'submodules/soomla-android-core' (https://github.com/soomla/soomla-android-core) registered for path 'submodules/soomla-android-core'
	Submodule 'submodules/soomla-ios-core' (https://github.com/soomla/soomla-ios-core) registered for path 'submodules/soomla-ios-core'
	Submodule 'submodules/soomla-wp-core' (https://github.com/soomla/soomla-wp-core) registered for path 'submodules/soomla-wp-core'
	Cloning into 'submodules/soomla-android-core'...
	remote: Counting objects: 763, done.
	remote: Total 763 (delta 0), reused 0 (delta 0), pack-reused 763
	Receiving objects: 100% (763/763), 682.69 KiB | 585.00 KiB/s, done.
	Resolving deltas: 100% (402/402), done.
	Checking connectivity... done.
	Submodule path 'submodules/soomla-unity3d-core/submodules/soomla-android-core': checked out 'fb834e77235a545b2c56f5aa308401b853a541e2'
	Cloning into 'submodules/soomla-ios-core'...
	remote: Counting objects: 865, done.
	remote: Total 865 (delta 0), reused 0 (delta 0), pack-reused 865
	Receiving objects: 100% (865/865), 3.78 MiB | 817.00 KiB/s, done.
	Resolving deltas: 100% (531/531), done.
	Checking connectivity... done.
	Submodule path 'submodules/soomla-unity3d-core/submodules/soomla-ios-core': checked out 'edf51c9769e8b3583dd28d0de6c774c4f20a0d87'
	Cloning into 'submodules/soomla-wp-core'...
	remote: Counting objects: 410, done.
	remote: Total 410 (delta 0), reused 0 (delta 0), pack-reused 410
	Receiving objects: 100% (410/410), 6.21 MiB | 822.00 KiB/s, done.
	Resolving deltas: 100% (211/211), done.
	Checking connectivity... done.
	Submodule path 'submodules/soomla-unity3d-core/submodules/soomla-wp-core': checked out '03b1cb1785e6f73f93d7f1288cd1f7ee31dad3d7'
	Cloning into 'submodules/wp-store'...
	remote: Counting objects: 611, done.
	remote: Total 611 (delta 0), reused 0 (delta 0), pack-reused 611
	Receiving objects: 100% (611/611), 5.98 MiB | 881.00 KiB/s, done.
	Resolving deltas: 100% (320/320), done.
	Checking connectivity... done.
	Submodule path 'submodules/wp-store': checked out '150979b6845d211deef77f09d1abc48d87531ce6'
	Submodule 'submodules/soomla-wp-core' (git@github.com:soomla/soomla-wp-core.git) registered for path 'submodules/soomla-wp-core'
	Cloning into 'submodules/soomla-wp-core'...
	Permission denied (publickey).
	fatal: Could not read from remote repository.

	Please make sure you have the correct access rights
	and the repository exists.
	Clone of 'git@github.com:soomla/soomla-wp-core.git' into submodule path 'submodules/soomla-wp-core' failed
	Failed to recurse into submodule path 'submodules/wp-store'

**Comment by p-i-** [comment]
The solution is to use `http` not `https`.
Could some Soom-La dev fix this in the documentation before closing the issue?

**Comment by borisspektor** [comment]
@p-i- it was fixed, can you please check that it works well for you?
