### ISSUE TITLE
Error at starting new project: SecurityException: No valid crossdomain policy available to allow access UnityEngine.WWW.get_text ()

### ISSUE THREAD

**Issue by cjdp25** [soomla/unity3d-store#531]
Hi, I'm starting a new project and importing Soomla from Unity Assets Store, first I import Soomla Store from here: [https://www.assetstore.unity3d.com/en/#!/content/6103](https://www.assetstore.unity3d.com/en/#!/content/6103) but as soon as it finishes importing the files I get the following error:

`Exception: Expected root element to be <cross-domain-policy>. found html instead
MonoForks.System.Windows.Browser.Net.FlashCrossDomainPolicy+Handler.OnStartElement (System.String name, IAttrList attrs)
MonoForks.Mono.Xml.MiniParser.Parse (IReader reader, IHandler handler)
MonoForks.System.Windows.Browser.Net.FlashCrossDomainPolicy.FromStream (System.IO.Stream originalStream)
MonoForks.System.Windows.Browser.Net.CrossDomainPolicyManager.BuildFlashPolicy (Boolean statuscodeOK, MonoForks.System.Uri uri, System.IO.Stream responsestream, System.Collections.Generic.Dictionary`2 responseheaders)
UnityEngine.WWW:get_isDone()
Soomla.SoomlaEditorScript:LatestVersionField(String, String, String, String) (at Assets/Soomla/Scripts/Core/Config/SoomlaEditorScript.cs:294)
Soomla.CoreSettings:OnInfoGUI() (at Assets/Soomla/Scripts/Core/Config/CoreSettings.cs:89)
Soomla.SoomlaEditorScript:OnInspectorGUI() (at Assets/Soomla/Scripts/Core/Config/SoomlaEditorScript.cs:196)
SoomlaSettingsEditor:OnInspectorGUI() (at Assets/Soomla/Editor/SoomlaSettingsEditor.cs:20)
UnityEditor.DockArea:OnGUI()`

and this error too:

`SecurityException: No valid crossdomain policy available to allow access
UnityEngine.WWW.get_text ()
Soomla.SoomlaEditorScript.LatestVersionField (System.String moduleId, System.String currentVersion, System.String versionPrompt, System.String downloadLink) (at Assets/Soomla/Scripts/Core/Config/SoomlaEditorScript.cs:295)
Soomla.CoreSettings.OnInfoGUI () (at Assets/Soomla/Scripts/Core/Config/CoreSettings.cs:89)
Soomla.SoomlaEditorScript.OnInspectorGUI () (at Assets/Soomla/Scripts/Core/Config/SoomlaEditorScript.cs:196)
SoomlaSettingsEditor.OnInspectorGUI () (at Assets/Soomla/Editor/SoomlaSettingsEditor.cs:20)
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor editor, Int32 editorIndex, Boolean rebuildOptimizedGUIBlock, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1231)
UnityEditor.DockArea:OnGUI()`

and when I go to _Window->Soomla->Edit Settings_ I don't see Soomla Store information.
So my question is: What is the correct way to import Soomla Store? I want to use **Store** and *_Profile_

**Comment by Blinkq** [comment]
Hello, @cjdp25  I guess this cozzed by Upgrade Link in Soomla Editor Setting.
we got task for this: https://trello.com/c/oIk6EWR1/246-improvement-remove-update-links-from-settings
so soon this will fixed.
If  you have no time to wait, you can try to remove it by yourself.
Try to Remove this line: https://github.com/soomla/unity3d-store/blob/master/Soomla/Assets/Soomla/Scripts/Store/Config/StoreSettings.cs#L91
