### ISSUE TITLE
IAPs not delivered. Fraud Protection issue?

### ISSUE THREAD

**Issue by Whyser** [soomla/unity3d-store#532]
Hello!

We've recently received an unusual amount of emails claiming they didn't receive the IAP they bought (on Google Play). Normally this would occur maybe once or twice every month (because of a crash or some other issue) but now we've received almost 2-3 a day for the last week (+ a few days maybe). We can assume that only maybe 20% of the "victims" actually report this issue meaning it's probably alot more then these 2 each day.

Did something recently happen with the fraud protection service? We haven't updated our app for maybe 2-3 months so we haven't really done anything. So my only guess is it has something to do with fraud protection/server issue.

Thanks!

**Comment by EugeneButusov** [comment]
Hi @Whyser, we're very sorry for possibly our fault. As we noticed on forums, fraud protection service was moved at https://iap.vedidev.com (Soomla supporting team since Grow will down). Some days ago we had some adjustments there and redirected verify.soom.la traffic there. Now all should be good. Could you please tell me if this issue is still here?

**Comment by Blinkq** [comment]
http://blog.soom.la/2016/05/grow-is-being-shut-down.html
Fraud Protection work, but moved to new server, suggest you to update plugins

**Comment by Whyser** [comment]
Yes I know they shut down. But there was also an announcement that it will continue to work until last of July (31th July). So what is the status on this @EugeneButusov ? Do we need to prepare for the new server to go down also, or will it stay up? :) (Also, do I need to update or not?)

It seems we've received fewer emails regarding this issue (but yesterday we received yet another two so I can not tell for sure).

**Comment by EugeneButusov** [comment]
Hi @Whyser, your old apps can use old URL (there is simple redirect), but in new versions URL was changed.

**Comment by Whyser** [comment]
Thanks for the answer @EugeneButusov !

I'm wondering have you seen any issues on the server? Because we are still receiving emails about IAPS not being delivered. Are you sure that your new server can handle the traffic appropriately? Thanks!

**Comment by Whyser** [comment]
Because of lack of response we'll have to disable Fraud Protection. I'm very disappointed that we had to do this and that our customers have to suffer because of this issue. Especially annoying that the announcement stated that we had until July 31th to implement alternative solution (or pay for some other solution), which obviously is not the case here.

**Comment by refaelos** [comment]
@EugeneButusov why are you guys not answering @Whyser? He clearly has a serious issue there.

Please take care of the Fraud protection server ASAP.

**Comment by EugeneButusov** [comment]
@Whyser, I looked at server logs and in common it looks correct. Could you please tell me privately (email evgeny at vedidev.com) possible product ids that can be failed?

**Comment by Whyser** [comment]
@EugeneButusov, I did email you, you did respond. You said in an email: "Purchases is failing in 20%, we’ll check why it happens". I asked you a few weeks ago for a further explanation as to what is or was wrong - no answer. Explain the cause and if you've fixed it, you can say so and close this?

**Comment by llaerto** [comment]
@Whyser Hello. Sorry for late answer. We are working about this problem now, when it will be decided we will write you about it. Thank you for waiting.

**Comment by khld85** [comment]
Hello I am having the same issue,
This is very weird because it is working on Samsung Note3 but it is not working on another device like Note5
please help me fix this, I am getting a low rating because of it

**Comment by llaerto** [comment]
Hello, thank you for message, we are working on it.

6 авг. 2016 г. 14:55 пользователь "khld85" <notifications@github.com>
написал:

**Comment by llaerto** [comment]
Hello. After investigate about your problem we have came to the conclusion, that this is not your and not our fault.
Google answer for some requests "Code 400, Invalid value", there are a lot of information in the internet about this, you can look about it too.
3 most often reason to refuse verification:
1) Rooted devices
2) Attemp to hack
3) Google bug, you can read more here: https://groups.google.com/forum/#!topic/google-apis-explorer-users/sJ5glcRva_s

Sorry for long waiting, and for what we can not help.
With best wishes.

**Comment by Whyser** [comment]
Okay thanks for confirming the issue.
