### ISSUE TITLE
[Andoid] AndroidJavaException After buying item

### ISSUE THREAD

**Issue by codexus** [soomla/unity3d-store#534]
Tested device (phone): Huawei p8, android 5.1
Soomla versions: core 1.3.2, store: 1.11.1

The exception is thrown after starting purchase.
 It occurs in Muffin rush example as in custom StoreAssets implementation.

[logcat.txt](https://github.com/soomla/unity3d-store/files/321315/logcat.txt)

**Comment by Blinkq** [comment]
@codexus Hi, tnx for your feedback, looks like problem in example, I will check it, and reply you soon.

**Comment by codexus** [comment]
Any clues what can be the issue? I'm trying to make it running, but without any results. Can you give me a hint, what can be possibly wrong?

**Comment by codexus** [comment]
It seems that the problem occurs only when I use store version 1.11.1. I've reimport the package from asset store and didn't click on the new version on the inspector, leaving the store version on 1.11.3, and everything is running like a charm. 

I will add my 5 cents: It's not a good habit to check if the version is newer comparing only the string values. It should cast the version to int, compare it, and then if the version is higher, tell the user that there is a new version on the server, otherwise this can lead to the situation described above. Cheers!
