### ISSUE TITLE
Exception and crash when calling RemoveGoodUpgrades on iOS

### ISSUE THREAD

**Issue by psykojello** [soomla/unity3d-store#535]
I've seen this question posted before, but I need specific help with my scenario. 

I'm Using Unity 5.1.3f and Soomla Store 1.8.2.

I can't upgrade to latest because it requires 5.2.4 and I can't upgrade my project for other reasons. 

Is there an older version of the plugin I can use where this issue is fixed? Or can you point me to a changelist which I can build. 

Here's my xcode log:

    VirtualGoodStorage: Removing upgrade information from virtual good: VG_LIFE_SAVER
    2016-06-18 09:49:42.439 MyProjectXX[4443:1948602] Uncaught exception:    
    NSInvalidArgumentException: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]

And from the stack:

	11  MyProjectXX                   0x00000001017ef088 +[StoreEventHandling postGoodUpgrade:withGoodUpgrade:] + 188
	12  MyProjectXX                   0x00000001017e70ac -[VirtualGoodStorage removeUpgradesFrom:withEvent:] + 252
	13  MyProjectXX                   0x0000000101736858 vgStorage_RemoveUpgrades + 156
	14  MyProjectXX                   0x000000010006f974 VirtualGoodsStorageIOS_vgStorage_RemoveUpgrades_m843 + 60
	15  MyProjectXX                   0x000000010006fe04 VirtualGoodsStorageIOS__removeUpgrades_m853 + 80
	16  MyProjectXX                   0x0000000100079b78 StoreInventory_RemoveGoodUpgrades_m989 + 1232

This post seems like the solution, but I'm not sure which changelist to use for it:
http://answers.soom.la/t/removegoodupgrades-crashes-on-ios/1032/2

**Comment by psykojello** [comment]
I have checked out version 1.8.6 which seems to contain the links. I'm not sure how to resolve the symbolic links on Windows. Do I also need to sync the core project? 

Sorry, I'm not familiar with Git. Everything's so confusing!

If someone can build a unity package for me for 1.8.6, I will be most grateful!

**Comment by psykojello** [comment]
I tried doing this on my mac instead and got a little further. 

Cloned the store repository recursively. Excellent. 

Checked out tag 1.8.6 in the soomla store repo. I'm not sure if this is correct - should I also check out a corresponding changelist in the core repository? 

Set up various environment variables, installed JDK, Ant, Android (this should really be documented)

ran ./build_all

After a few attempts I got most of it building, but it fails to build unityandroidstore:


compile.module.unityandroidstore.production:
    [mkdir] Created dir: /Users/Junsh/soomla/unity3d-store/soomla-native/projects/unity-android-store/out/production/UnityAndroidStore
    [javac] /Users/Junsh/soomla/unity3d-store/soomla-native/projects/unity-android-store/module_unityandroidstore.xml:90: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 1 source file to /Users/Junsh/soomla/unity3d-store/soomla-native/projects/unity-android-store/out/production/UnityAndroidStore
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
    [javac] /Users/Junsh/soomla/unity3d-store/soomla-native/projects/unity-android-store/src/com/soomla/unity/StoreEventHandler.java:4: error: cannot find symbol
    [javac] import com.soomla.BusProvider;
    [javac]                  ^
    [javac]   symbol:   class BusProvider
    [javac]   location: package com.soomla


Any suggestions? I'm not sure if anyone even looks at these issues - I prefered Soomla Answers tbh :(

**Comment by Blinkq** [comment]
@psykojello  Hi,

> Set up various environment variables, installed JDK, Ant, Android (this should really be documented)

Yeah, agree with that.

What Java version you are using ?

**Comment by psykojello** [comment]
I installed 8u91 which shows up in the path as:
jdk 1.8.0.91

**Comment by psykojello** [comment]
I have a feeling my git commands are wrong. I was able to build the latest.

Could someone help me with the right sequence of commands to build 1.8.6?

1. Clone recurisvely
git clone --recursive https://github.com/soomla/unity3d-store.git

2. Sync/Update/Checkout branch tagged "v1.8.6"
git checkout ..... (not sure of the command here, so I used the GitKraken UI to checkout this branch)

3. run ./build_all
 - this step fails towards the end

4. run ./create_deploys from the "deploy" folder.

**Comment by psykojello** [comment]
I think my problem is that I'm not using Git properly. How do I "sync" to or "update" to the changelist/branch tagged "v1.8.6"?

I was able to successfully build latest from the repo, but not any earlier version.

Not sure if I need to "checkout" or "pull" or "branch"

**Comment by psykojello** [comment]
It might not have been clear from the log above, but these lines:
[javac] import com.soomla.BusProvider;
[javac] ^

the caret symbol is pointing to the dot inbetween soomla and BusProvider. 

looks like it can't find a definition for BusProvider.

**Comment by Blinkq** [comment]
Just realised that if you want 1.8.6, then you need to downgrade submodules too

**Comment by psykojello** [comment]
I thought that might be it. Is there a command to do this in Git or should I clone each submodule separately and build them?

**Comment by Blinkq** [comment]
Yeah, can't say for sure, but I did in noob way, and cloned each submodule separately. Write your mail, I will send you packages.

**Comment by psykojello** [comment]
thank you so much! its psykojello@gmail.com

**Comment by psykojello** [comment]
Hi @Blinkq , did you get a chance to email it yet? I don't see an email from you.  thanks once again!

**Comment by psykojello** [comment]
Got it, thanks! Removing my post with the email address.
