### ISSUE TITLE
Soomla API Set UP!! Google Play developer account

### ISSUE THREAD

**Issue by elijahrender** [soomla/unity3d-store#537]
Hello everyone, I have set up soomla with my game and I am trying to use fraud protection. I read the docs about creating client ID, secret, and also refresh token. I made a google developer console project which has the client id and secret in it, and found my refresh token from there. Ok, that parts done, and when I go to the "Game Services" tab on my Google Play Developer account and click on my game, it says that it is connected to the correct API console project(the one I just made for the ID's). However, my question is this,... when I go to the Settings in my Google Play Developer account page, and click on the tab that says "API Access", it says "To access the API you must link your account to a Google Developer Project" with a button underneath saying "Create new project". I click the button and automatically, it created a Linked project called "Google Play Android Developer" by default. Whats this for? Am I even supposed to make a linked project for the api access? (like, is it required for Soomla Fraud protection to work????) If I do need it for Soomla, how would I connect that project with my current project I made? Please help!

**Comment by Blinkq** [comment]
@elijahrender  As I understood you,  you did all right, and know you 
you can start from step "3. Create A Web Application OAuth 2.0 ID in..."
http://know.soom.la/soomla/android/store/store_googleplayverification

**Comment by elijahrender** [comment]
Hello @blinkq thank you for confirmation! I already have my client id, client secret, and refresh token from a project I made(web application) I think the problem is just linking the project to my google play developer account. I believe that's step 2. However , my game is linked to the correct project, it's just the Api access tab I'm worried about. How can I link the project to the "api access" tab in google play Dev account? Or is that even required?

**Comment by Blinkq** [comment]
@elijahrender  So, you did all, but fraud protection want work ?

**Comment by elijahrender** [comment]
@Blinkq  yea it wont work, keeps crashing

**Comment by Blinkq** [comment]
@elijahrender share your logs when you trying to buy, please

**Comment by elijahrender** [comment]
im sorry but i dont know how to do that for android. i click the two boxes for debugging in soomla settings but i dont know where to go after that

**Comment by Blinkq** [comment]
@elijahrender 
1) Enable Debug Unity and Debug Native in Soomla settings (Window -> Soomla -> Edit Settings);
2) When you're building your project in Unity - please enable Development build option;
3) Look for log output (console in iOS or LogCat in Android).
For Android I am using [Monitor](https://developer.android.com/studio/profile/monitor.html) you can filter massages, and see all output of your app

**Comment by elijahrender** [comment]
ok this is my first time ever using the logcat, so i think this is the right thing to paste

`06-25 19:08:10.897 20341-20341/com.ElijahRender.Invader E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.ElijahRender.Invader, PID: 20341
                                                                          java.lang.Error: FATAL EXCEPTION [main]
                                                                          Unity version     : 5.3.5f1
                                                                          Device model      : HTC HTCONE
                                                                          Device fingerprint: htc/sprint_wwe/m7wls:5.0.2/LRX22G/499067.10:user/release-keys
                                                                          
                                                                          Caused by: java.lang.AbstractMethodError: abstract method "void com.soomla.store.billing.IIabService.launchPurchaseFlow(java.lang.String, com.soomla.store.billing.IabCallbacks$OnPurchaseListener, java.lang.String)"
                                                                              at com.soomla.store.SoomlaStore$5.success(SoomlaStore.java:450)
                                                                              at com.soomla.store.billing.google.GooglePlayIabService$OnIabSetupFinishedListener.onIabSetupFinished(GooglePlayIabService.java:477)
                                                                              at com.soomla.store.billing.IabHelper$7.run(IabHelper.java:405)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:155)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5696)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
06-25 19:08:10.907 20341-20370/com.ElijahRender.Invader I/Unity: SOOMLA StoreEvents SOOMLA/UNITY onBillingSupported
                                                                 UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
                                                                 UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
                                                                 UnityEngine.Logger:Log(LogType, Object)
                                                                 UnityEngine.Debug:Log(Object)
                                                                 Soomla.SoomlaUtils:LogDebug(String, String) (at C:\Users\zachp_000.GERALDINEPC\Documents\Invader\Assets\Soomla\Scripts\Core\SoomlaUtils.cs:50)
                                                                 Soomla.Store.StoreEvents:onBillingSupported(String) (at C:\Users\zachp_000.GERALDINEPC\Documents\Invader\Assets\Soomla\Scripts\Store\StoreEvents.cs:424)
                                                                  
                                                                 (Filename: C Line: 0)
06-25 19:08:10.907 20341-20370/com.ElijahRender.Invader I/Unity: SOOMLA StoreEvents SOOMLA/UNITY onIabServiceStarted
                                                                 UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
                                                                 UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
                                                                 UnityEngine.Logger:Log(LogType, Object)
                                                                 UnityEngine.Debug:Log(Object)
                                                                 Soomla.SoomlaUtils:LogDebug(String, String) (at C:\Users\zachp_000.GERALDINEPC\Documents\Invader\Assets\Soomla\Scripts\Core\SoomlaUtils.cs:50)
                                                                 Soomla.Store.StoreEvents:onIabServiceStarted(String) (at C:\Users\zachp_000.GERALDINEPC\Documents\Invader\Assets\Soomla\Scripts\Store\StoreEvents.cs:908)
                                                                  
                                                                 (Filename: C Line: 0)
06-25 19:08:10.927 20341-20370/com.ElijahRender.Invader I/Unity: SOOMLA StoreEvents SOOMLA/UNITY onMarketPurchaseStarted: {"itemId":"energy_unlimited"}
                                                                 UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
                                                                 UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
                                                                 UnityEngine.Logger:Log(LogType, Object)
                                                                 UnityEngine.Debug:Log(Object)
                                                                 Soomla.SoomlaUtils:LogDebug(String, String) (at C:\Users\zachp_000.GERALDINEPC\Documents\Invader\Assets\Soomla\Scripts\Core\SoomlaUtils.cs:50)
                                                                 Soomla.Store.StoreEvents:onMarketPurchaseStarted(String) (at C:\Users\zachp_000.GERALDINEPC\Documents\Invader\Assets\Soomla\Scripts\Store\StoreEvents.cs:716)
                                                                  
                                                                 (Filename: C Line: 0)
06-25 19:08:10.937 20341-20370/com.ElijahRender.Invader I/Unity: SOOMLA/UNITY StoreInfo Trying to fetch an item with itemId: energy_unlimited
                                                                 UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
                                                                 UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
                                                                 UnityEngine.Logger:Log(LogType, Object)
                                                                 UnityEngine.Debug:Log(Object)
                                                                 Soomla.SoomlaUtils:LogDebug(String, String) (at C:\Users\zachp_000.GERALDINEPC\Documents\Invader\Assets\Soomla\Scripts\Core\SoomlaUtils.cs:50)
                                                                 Soomla.Store.StoreInfo:GetItemByItemId(String) (at C:\Users\zachp_000.GERALDINEPC\Documents\Invader\Assets\Soomla\Scripts\Store\data\StoreInfo.cs:126)
                                                                 Soomla.Store.StoreEvents:onMarketPurchaseStarted(String) (at C:\Users\zachp_000.GERALDINEPC\Documents\Invader\Assets\Soomla\Scripts\Store\StoreEvents.cs:720)
                                                                  
                                                                 (Filename: C Line: 0)
06-25 19:08:13.800 20341-20351/com.ElijahRender.Invader W/art: Suspending all threads took: 57.164ms
06-25 19:08:19.966 20341-20341/com.ElijahRender.Invader D/Process: killProcess, pid=20341
06-25 19:08:19.986 20341-20341/com.ElijahRender.Invader D/Process: com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException:138 com.soomla.SoomlaApp$1.uncaughtException:67 com.unity3d.player.u.uncaughtException:-1 
`

**Comment by Blinkq** [comment]
@elijahrender  Can you post next lines to 
Nice. This is it, but this log ends just right before place that we need =)

> Soomla.Store.StoreEvents:onMarketPurchaseStarted(String) (at C:\Users\zachp_000.GERALDINEPC\Documents\Invader\Assets\Soomla\Scripts\Store\StoreEvents.cs:720)

after this line there should be something

**Comment by elijahrender** [comment]
Ok hold on

**Comment by elijahrender** [comment]
06-26 05:29:18.427 10435-10435/com.ElijahRender.Invader E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.ElijahRender.Invader, PID: 10435
                                                                          java.lang.Error: FATAL EXCEPTION [main]
                                                                          Unity version     : 5.3.5f1
                                                                          Device model      : HTC HTCONE
                                                                          Device fingerprint: htc/sprint_wwe/m7wls:5.0.2/LRX22G/499067.10:user/release-keys
                                                                          
                                                                          Caused by: java.lang.AbstractMethodError: abstract method "void com.soomla.store.billing.IIabService.launchPurchaseFlow(java.lang.String, com.soomla.store.billing.IabCallbacks$OnPurchaseListener, java.lang.String)"
                                                                              at com.soomla.store.SoomlaStore$5.success(SoomlaStore.java:450)
                                                                              at com.soomla.store.billing.google.GooglePlayIabService$OnIabSetupFinishedListener.onIabSetupFinished(GooglePlayIabService.java:477)
                                                                              at com.soomla.store.billing.IabHelper$7.run(IabHelper.java:405)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:155)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5696)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
06-26 05:29:18.427 10435-10509/com.ElijahRender.Invader I/Unity: SOOMLA StoreEvents SOOMLA/UNITY onBillingSupported
                                                                 UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
                                                                 UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
                                                                 UnityEngine.Logger:Log(LogType, Object)
                                                                 UnityEngine.Debug:Log(Object)
                                                                 Soomla.SoomlaUtils:LogDebug(String, String) (at C:\Users\zachp_000.GERALDINEPC\Documents\Invader\Assets\Soomla\Scripts\Core\SoomlaUtils.cs:50)
                                                                 Soomla.Store.StoreEvents:onBillingSupported(String) (at C:\Users\zachp_000.GERALDINEPC\Documents\Invader\Assets\Soomla\Scripts\Store\StoreEvents.cs:424)
                                                                  
                                                                 (Filename: C Line: 0)
06-26 05:29:18.427 10435-10509/com.ElijahRender.Invader I/Unity: SOOMLA StoreEvents SOOMLA/UNITY onIabServiceStarted
                                                                 UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
                                                                 UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
                                                                 UnityEngine.Logger:Log(LogType, Object)
                                                                 UnityEngine.Debug:Log(Object)
                                                                 Soomla.SoomlaUtils:LogDebug(String, String) (at C:\Users\zachp_000.GERALDINEPC\Documents\Invader\Assets\Soomla\Scripts\Core\SoomlaUtils.cs:50)
                                                                 Soomla.Store.StoreEvents:onIabServiceStarted(String) (at C:\Users\zachp_000.GERALDINEPC\Documents\Invader\Assets\Soomla\Scripts\Store\StoreEvents.cs:908)
                                                                  
                                                                 (Filename: C Line: 0)
06-26 05:29:18.427 10435-10509/com.ElijahRender.Invader I/Unity: SOOMLA StoreEvents SOOMLA/UNITY onMarketPurchaseStarted: {"itemId":"energy_unlimited"}
                                                                 UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
                                                                 UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
                                                                 UnityEngine.Logger:Log(LogType, Object)
                                                                 UnityEngine.Debug:Log(Object)
                                                                 Soomla.SoomlaUtils:LogDebug(String, String) (at C:\Users\zachp_000.GERALDINEPC\Documents\Invader\Assets\Soomla\Scripts\Core\SoomlaUtils.cs:50)
                                                                 Soomla.Store.StoreEvents:onMarketPurchaseStarted(String) (at C:\Users\zachp_000.GERALDINEPC\Documents\Invader\Assets\Soomla\Scripts\Store\StoreEvents.cs:716)
                                                                  
                                                                 (Filename: C Line: 0)
06-26 05:29:18.427 10435-10509/com.ElijahRender.Invader I/Unity: SOOMLA/UNITY StoreInfo Trying to fetch an item with itemId: energy_unlimited
                                                                 UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
                                                                 UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
                                                                 UnityEngine.Logger:Log(LogType, Object)
                                                                 UnityEngine.Debug:Log(Object)
                                                                 Soomla.SoomlaUtils:LogDebug(String, String) (at C:\Users\zachp_000.GERALDINEPC\Documents\Invader\Assets\Soomla\Scripts\Core\SoomlaUtils.cs:50)
                                                                 Soomla.Store.StoreInfo:GetItemByItemId(String) (at C:\Users\zachp_000.GERALDINEPC\Documents\Invader\Assets\Soomla\Scripts\Store\data\StoreInfo.cs:126)
                                                                 Soomla.Store.StoreEvents:onMarketPurchaseStarted(String) (at C:\Users\zachp_000.GERALDINEPC\Documents\Invader\Assets\Soomla\Scripts\Store\StoreEvents.cs:720)
                                                                  
                                                                 (Filename: C Line: 0)
06-26 05:29:20.379 10435-10444/com.ElijahRender.Invader W/art: Suspending all threads took: 99.435ms
06-26 05:29:23.012 10435-10435/com.ElijahRender.Invader D/Process: killProcess, pid=10435
06-26 05:29:23.042 10435-10435/com.ElijahRender.Invader D/Process: com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException:138 com.soomla.SoomlaApp$1.uncaughtException:67 com.unity3d.player.u.uncaughtException:-1

**Comment by Blinkq** [comment]
@elijahrender  Can you send me full log to blinkq@vedidev.com ?

**Comment by Blinkq** [comment]
@elijahrender  Got it.
Here the massage I didn't like, could be soomla bug:
`AndroidJavaException: java.lang.AbstractMethodError: abstract method "void com.soomla.store.billing.IIabService.launchPurchaseFlow(java.lang.String, com.soomla.store.billing.IabCallbacks$OnPurchaseListener, java.lang.String)"`

I will check it, and reply you soon.

**Comment by elijahrender** [comment]
ok, thank you very much!

**Comment by Blinkq** [comment]
@elijahrender  How did you get and install Soomla package ?
```
06-26 05:29:07.865 10435-10509/com.ElijahRender.Invader I/Unity: AndroidJavaException: java.lang.AbstractMethodError: abstract method "void com.soomla.store.billing.IIabService.launchPurchaseFlow(java.lang.String, com.soomla.store.billing.IabCallbacks$OnPurchaseListener, java.lang.String)"
                                                                 java.lang.AbstractMethodError: abstract method "void com.soomla.store.billing.IIabService.launchPurchaseFlow(java.lang.String, com.soomla.store.billing.IabCallbacks$OnPurchaseListener, java.lang.String)"
                                                                     at com.soomla.store.SoomlaStore$5.success(SoomlaStore.java:450)
                                                                     at com.soomla.store.billing.google.GooglePlayIabService.startIabHelper(GooglePlayIabService.java:261)
                                                                     at com.soomla.store.billing.google.GooglePlayIabService.initializeBillingService(GooglePlayIabService.java:68)
                                                                     at com.soomla.store.SoomlaStore.buyWithMarket(SoomlaStore.java:386)
                                                                     at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
                                                                     at com.unity3d.player.UnityPlayer.a(Unknown Source)
                                                                     at com.unity3d.player.UnityPlayer$b.run(Unknown Source)
                                                                   at UnityEngine.AndroidJNISafe.CheckException () [0x00085] in /Users/b
```
Your soomla plugin corrupted.

**Comment by elijahrender** [comment]
I got it from asset store

**Comment by elijahrender** [comment]
i had the previous version, and just upgraded

**Comment by elijahrender** [comment]
i had it when it was free, but now i believe it costs $50, but i still got it free by upgrading

**Comment by elijahrender** [comment]
what should i do?

**Comment by Blinkq** [comment]
@elijahrender  Than, package ok, try to remove plugin and import again.

**Comment by elijahrender** [comment]
Ok, also i downloaded this on two differenet computeres and projects (games)and they both crashed, so if this doesnt work, is there any other method?

**Comment by elijahrender** [comment]
Thank you so much!! (:
