### ISSUE TITLE
Unable to build Android - Unsupported class file version 52.0

### ISSUE THREAD

**Issue by crunchbury** [soomla/unity3d-store#541]
Hi,
I am trying to get my project going on Android but I'm completely unable to build it. I get the following error when it goes to convert my classes to dex format, and appears to be erroring out in Soomla.

> CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
> /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/bin/java -Xmx2048M -Dcom.android.sdkmanager.toolsdir="/Users/gavin/Library/Android/sdk/tools" -Dfile.encoding=UTF8 -jar "/Applications/UnityX/PlaybackEngines/AndroidPlayer/Tools/sdktools.jar" -
> 
> stderr[
> 
> PARSE ERROR:
> unsupported class file version 52.0
> ...while parsing com/soomla/rewards/VirtualItemReward.class
> 
> PARSE ERROR:
> unsupported class file version 52.0
> ...while parsing com/soomla/store/billing/google/Consts.class
> 
> PARSE ERROR:
> unsupported class file version 52.0
> ...while parsing com/soomla/AndroidBus.class
> 
> PARSE ERROR:
> unsupported class file version 52.0
> ...while parsing com/soomla/unity/StoreEventHandler.class
> 
> PARSE ERROR:
> unsupported class file version 52.0
> ...while parsing com/soomla/core/unity/SoomlaBridge.class
> 5 errors; aborting
> ]

I have tried a lot of Googling around but I'm unable to find a solution and I'm completely blocked at the moment. I'm using OSX and have updated Java. The only directory inside my JavaVirtualMachines directory is jdk1.8.0_92.jdk. I cloned Soomla from Github recursively, built all from the OSX terminal, and then ran the deploy commands to generate packages. The versions reported in the editor are-

Core 1.3.2
Store 1.11.3

Please help! I am totally blocked and not sure what to do.

Thank you!

**Comment by jajool** [comment]
i think in order to build soomla you need jdk1.7. try downloading it and set the path environment to jdk1.7.

**Comment by Blinkq** [comment]
yeah, this error appears when you builded your libs with jdk 1.8, while you should use 1.7

**Comment by crunchbury** [comment]
Thanks, I got ride of 1.8 and installed 1.7.0_79. Looks like I get a little further, but I still fail out when compiling resources:

> -bootclasspath "/Users/gavin/Library/Android/sdk/platforms/android-24/android.jar" -d "/Users/gavin/dizzyknightr2/Restore/Temp/StagingArea/bin/classes" -source 1.6 -target 1.6 -encoding UTF-8 "com/chartboost/sdk/unity/R.java" "com/google/android/gms/R.java" "com/heyzap/R.java" "com/megasweet/DizzyKnight/R.java" "com/soomla/SoomlaApp/R.java" "com/unity3d/ads/android/R.java"
> warning: /Users/gavin/Library/Android/sdk/platforms/android-24/android.jar(java/lang/Object.class): major version 52 is newer than 51, the highest major version supported by this compiler.
>   It is recommended that the compiler be upgraded.

It looks like maybe it's looking for 1.6?

**Comment by jajool** [comment]
You have to download android sdk platform android 19 and build tools 19.

**Comment by crunchbury** [comment]
Thank you so much for the help. I got a little further but it seems to still be complaining about 52.0 somewhere in my system.

> Error building Player: CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
> /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java -Xmx2048M -Dcom.android.sdkmanager.toolsdir="/Users/gavin/Library/Android/sdk/tools" -Dfile.encoding=UTF8 -jar "/Applications/UnityX/PlaybackEngines/AndroidPlayer/Tools/sdktools.jar" -
> 
> stderr[
> Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/dx/command/Main : Unsupported major.minor version 52.0
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
> 	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
> 	at java.security.AccessController.doPrivileged(Native Method)
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:274)
> 	at SDKMain.main(SDKMain.java:127)
> ]
>
