### ISSUE TITLE
soomla use previous product id in ios

### ISSUE THREAD

**Issue by Hamed1984** [soomla/unity3d-store#547]
hi
i am using soomla 1.8.6.
in ios . in my first build i used a product id like "com.company.creditpack1"  and it not worked. so i figure out that i can't use '.' dot in product id in apple store so i change it to only "creditpack1" and build again
and choose append while building project. my problem is that when i test in device in logs soomla says

SOOMLA SoomlaStore: An error occured for product id "com.company.creditpack1" with code "0" and description "Error Domain=SKErrorDomain Code=0 "Cannot connect to iTunes Store"

but there is no code for id "com.company.creditpack1" in my code and soomla still use previous version

did soomla cache product names somewhere, so i could delete that?

**Comment by Blinkq** [comment]
Hi, did you tried to fully remove app before install it again ?

**Comment by Hamed1984** [comment]
yes and it solved my problem. thanks
