### ISSUE TITLE
How to get Item price from Market? (CafeBazaar)

### ISSUE THREAD

**Issue by EmpireWorld** [soomla/unity3d-store#560]
Hi Everyone.
I want to **get** my item **price** from **bazaar**.
How to do it?

**Comment by webschnecke** [comment]
I can give you a way how I do it for c++ (cocos2d-x) maby you can translate it for you?

**Comment by EmpireWorld** [comment]
I need it in c#. do you can give me it in c# or not do this way.

**Comment by webschnecke** [comment]
I hope this help you a littlest ;-) I can cast with this way a specific item from the store with alls its infos.


`//COINS PACK 01
    CCVirtualItem *coinsPackID_01;
    std::string coinsPackID_Price_01;
    std::string coinsPackID_Title_01;
    std::string coinsPackID_Descr_01;
    double coinsPriceSoomlaDB_01;
    
    coinsPackID_01 = CCStoreInfo::sharedStoreInfo()->getItemByItemId(COINS_PACK_ID_01, &soomlaError);
    if (!soomlaError) {
        CC_ASSERT(coinsPackID_01);
        CCPurchasableVirtualItem *purchasableVirtualItem = dynamic_cast<CCPurchasableVirtualItem *>(coinsPackID_01);
        CC_ASSERT(purchasableVirtualItem);
        CCPurchaseWithMarket *purchaseWithMarket = dynamic_cast<CCPurchaseWithMarket *>(purchasableVirtualItem->getPurchaseType());
        CC_ASSERT(purchaseWithMarket);
        coinsPackID_Price_01    = purchaseWithMarket->getMarketItem()->getMarketPriceAndCurrency()->getCString();
        coinsPackID_Title_01    = purchaseWithMarket->getMarketItem()->getMarketTitle()->getCString();
        coinsPackID_Descr_01    = purchaseWithMarket->getMarketItem()->getMarketDescription()->getCString();
        coinsPriceSoomlaDB_01   = purchaseWithMarket->getMarketItem()->getPrice()->getValue();
    }
`


have fun ;-)

**Comment by EmpireWorld** [comment]
Thanks. but i need it in C# language.

All the bests.
